src/exla/exla.cc
src/exla/exla_nif_util.h

I'm pretty sure this does it. We call `enif_release_resource` after the object is created and then `free` runs when the resource is garbage collected so I used the `delete` operator to free up that dynamically allocated memory

Address memory leaks

---

.gitignore
.gitmodules
Makefile
README.md
mix.exs

This allows EXLA to share most of the build steps between versions when installed as a package.

Use a global tensorflow checkout

---

c_src/exla/BUILD
c_src/exla/exla.cc
c_src/exla/exla_allocator.cc
c_src/exla/exla_allocator.h
c_src/exla/exla_client.cc
c_src/exla/exla_client.h
c_src/exla/exla_device.cc
c_src/exla/exla_device.h
c_src/exla/exla_nif_util.cc
c_src/exla/exla_nif_util.h
lib/exla/local_executable.ex
lib/exla/nif.ex
test/exla/local_executable_test.exs

Only optimized on CPU right now, benchmark showing virtually no difference between "pre-loaded" and not pre-loaded:
```
Name                             ips        average  deviation         median         99th %
xla cpu dot pre-loaded        2.58 K      387.98 μs    ±11.64%      380.02 μs      618.88 μs
xla cpu dot                   2.51 K      398.85 μs    ±12.73%      388.67 μs      633.52 μs
elixir dot                  0.0235 K    42494.06 μs    ±20.26%    41933.57 μs    61825.09 μs
Comparison: 
xla cpu dot pre-loaded        2.58 K
xla cpu dot                   2.51 K - 1.03x slower +10.87 μs
elixir dot                  0.0235 K - 109.53x slower +42106.08 μs
```

Zero-Copy Transfers

---

nx/lib/nx/defn.ex

no function `Nx.multipy` exists, doc should updated to use `Nx.multiply` instead

Improve defn.ex docs

---

nx/lib/nx/type.ex

Small correction to docs for `Nx.Type.cast_scalar!/2`

Improve doc for Nx.Type.cast_scalar!

---

nx/lib/nx/backend.ex

no type NX.Tensor.axes() exits, should be Nx.Tensor.axes() instead

no type NX.Tensor.axes() exists

---

exla/test/exla/defn_expr_test.exs
nx/lib/nx.ex

This PR aims to implement the 0-norm, 1-norm and 2-norm cited in #157 via the `p_norm/2` function

Implement p-norm definitions

---

.tool-versions
nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

This is for progress in issue #161  .
- Added gradients for `arccos` and `arcsin`.
- Added a test that checks the gradients of those functions.
- Moved some grad functions around to be closer to each other.

Gradients for inverse trig functions (arccos, arcsin, arctan)

---

nx/lib/nx.ex

This PR adds a couple of improvements to Nx's documentation. 
Also, I am not sure where the correct place would be to add this comment, but I noticed that the function `Nx.shape/1` and its variants do not have any associated tests. 
Was that intentional?
If not, can the tests for this function be added?

Improve docs

---

nx/lib/nx/shared.ex

This PR fixes `Nx.Shared.erf_fallback/1` with values near 0.0 to behave much closer to `:math.erf/1` by using a different approximation.
Ported from: [XLA's f32  implementation of erf](https://github.com/tensorflow/tensorflow/blob/0e6b3a307f6363a9ee9dc9e03a8a0350c7668799/tensorflow/compiler/xla/client/lib/math.cc#L301-L317)
Before:
```elixir
iex(1)> Nx.Shared.erf_fallback(5.5)
0.9999999999999959
iex(2)> :math.erf(5.5)             
0.9999999999999927
iex(3)> Nx.Shared.erf_fallback(0.1)
0.9202851829545222
iex(4)> :math.erf(0.1)             
0.1124629160182849
```
After:
```elixir
iex(17)> Nx.Shared.erf_fallback(5.5)
1.0
iex(18)> :math.erf(5.5)             
0.9999999999999927
iex(19)> Nx.Shared.erf_fallback(0.1)
0.11246291096244612
iex(20)> :math.erf(0.1)             
0.1124629160182849
```

Fix Nx.Shared.erf_fallback/1 near zero

---

exla/Makefile
exla/Makefile.win
exla/README.md
exla/docker/Dockerfile.cuda
exla/docker/Dockerfile.rocm

This is about as much of a hack as you can get, but basically we just comment out 4 parts of the TensorFlow build workflow so it doesn't check for the NumPy dependency up front. LLVM requires Python later on so we can't get rid of that, but we no longer need to depend on NumPy just to build.
I think this `sed` will just keep prepending comments to those lines, though.

Remove NumPy dependency

---

exla/test/exla/defn_expr_test.exs
nx/lib/nx.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/grad.ex
nx/lib/nx/shared.ex
nx/test/nx/defn/grad_test.exs
nx/test/nx/shared_test.exs

This PR adds `erf_inv/1` operation to `Nx`, `Nx.Backend`, and `EXLA`.
```python
In [2]: from scipy import special
In [3]: special.erfinv(0.999)
Out[3]: 2.3267537655135464
In [4]: special.erfinv(0.01)
Out[4]: 0.008862501280950608
```
```elixir
iex(1)> Nx.erf_inv(0.999)
#Nx.Tensor<
f64
2.326753756865462
>
iex(2)> Nx.erf_inv(0.01) 
#Nx.Tensor<
f64
0.008862500728738846
>
```
+ [erf_inv in XLA](https://github.com/tensorflow/tensorflow/blob/0e6b3a307f6363a9ee9dc9e03a8a0350c7668799/tensorflow/compiler/xla/client/lib/math.cc#L340-L390)
+ [erf_inv's grad in Jax](https://github.com/google/jax/blob/7e040c0a89b7b1f5c3607623d67c811d977470f4/jax/_src/lax/lax.py#L2434-L2436)

Add erf_inv/1 to Nx and enable in EXLA

---

nx/lib/nx/defn.ex

I fixed the warnings that `mix docs` generates as below:
```
$ mix docs
Generating docs...
warning: documentation references "Nx.Defn.Kernel.max_unsigned_type/2" but it is undefined or private
lib/nx/defn.ex:2: Nx.Defn
warning: documentation references "Nx.Defn.Kernel.max_signed_type/2" but it is undefined or private
lib/nx/defn.ex:2: Nx.Defn
warning: documentation references "Nx.Defn.Kernel.max_float_type/2" but it is undefined or private
lib/nx/defn.ex:2: Nx.Defn
View "html" docs at "doc/index.html"
```

fix warnings when `mix docs` invoked

---

nx/README.md

Just fixing 404 link in README.md.

Fix 404 link to EXLA in README.md

---

nx/lib/nx.ex
nx/test/nx_test.exs

+ adds tests to increase the code coverage of the Nx top-level module to 100%
Before:
```
90.02% | Nx
-----------|--------------------------
90.03% | Total
```
After:
```
100.00% | Nx
-----------|--------------------------
92.69% | Total
```
+ updates the error messages of many errors to be more clear and/or less wordy
+ fixes errors being raised inside some errors
+ adds some missed validation cases
+ removes at least 1 unreachable line - `mean_den` only deals with normalized axes which cannot be negative
+ formats `lib/nx.ex` and `test/nx_test.exs`
Most of the new tests cover invalid or exception-raising options, options that can take multiple forms (and don't show up in the docs for brevity), or options/args that require a very specific value/shape/length to raise an exception.
Despite …

Increase Nx module testing coverage to 100%

---

nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/shape.ex
nx/test/nx_test.exs

This PR adds an implementation for the Householder QR decomposition method. The function signature was designed for Numpy compatibility.
related to #157

Add QR decomposition

---

nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

This commit adds gradient for the following inverse hyperbolic functions:
- Arcsinh
- Arccosh
- Arctanh
PS: Shouldn't this functions drop the c? Wikipedia has some information on this. [Notation](https://en.wikipedia.org/wiki/Inverse_hyperbolic_functions#Notation)

Add gradient for inverse hyperbolic functions

---

exla/README.md

Per the below slack request from @seanmor5 I have added a section on compiling in ElixirLS. I also added a note about gitref vs local path, as this was a mistake I made early on that cost me many hours in unnecessary recompilation.

Add note about ElixirLS per request from Sean. Add note about gitref vs local path.

---

exla/README.md

I couldn't get exla to build with asdf installed python but found a workaround that uses the homebrew installed version of Python.
This adds a note to the README for others in the same position.

Update README for asdf installed pythons

---

exla/lib/exla/aot/codegen.ex

@seanmor5 I have ran some tests locally and I didn't  see any segfaults. Thoughts?

Set AllocMode to avoid copying input data on AOT

---

exla/README.md

Ahoy!
I've been using `asdf` with `direnv` via the `asdf-direnv` plugin without issue. I saw the `README` update the other day, and figured I could definitely add what worked for me in regards to `asdf`. FWIW, `direnv` makes `asdf` really wonderful where it was once pretty darn rough to live with.
While I didn't explicitly add my versions to the README, I was able to successfully build `EXLA` with `asdf` on Linux and CUDA working quite well:
```
erlang ref:master
python 3.8.8 2.7.18
bazel 3.1.0
elixir master
use asdf
EXLA_FLAGS=--config=cuda
```
I'm more than happy to adjust the language, formatting, or otherwise alter the details I've added (including just deleting my changes, haha 😺)-- please, just let me know. Thanks everyone's hard work on this! It's soooo freakin' cool.
P.S. I can …

Update README with direnv+asdf python workaround

---

exla/test/exla/defn_expr_test.exs
nx/lib/nx.ex
nx/test/nx/defn/grad_test.exs
nx/test/test_helper.exs

This is what JAX uses to test against NumPy, a bit more precise than float rounding. Also updates `check_grads!` to support n-D output so we can use finite differences for all of the gradient tests rather than just comparing against JAX output

Add and use allclose? when testing

---

exla/c_src/exla/exla.cc
exla/c_src/exla/exla_client.cc
exla/c_src/exla/exla_client.h
exla/config/runtime.exs
exla/lib/exla/client.ex
exla/lib/exla/nif.ex

Allows users to tune preallocation which makes troubleshooting OOM easier: https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

Add memory options

---

nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/shape.ex

This PR implements LU decomposition for #157, as per the [scipy.linalg.lu](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html).
No options are supported besides our own `:eps` and `*_names` because:
- overwrite_a: this doesn't make sense for Elixir
- permute_l: makes the function's return type polymorphic so it wasn't implemented
- check_finite: we don't support infinities yet

feat: add lu decomposition

---

nx/lib/nx/heatmap.ex
nx/test/nx/heatmap_test.exs

`@hauleth` reported in the `#nx` that the Heatmap inspect had an unexpected behavior for asymetric tensors (i.e. 4x2). This PR aims to fix this problem.

fix: change col and row for heatmatp inspect

---

nx/lib/nx.ex
nx/lib/nx/shape.ex

Implements the `Nx.tile/2` function as per the [Numpy docs](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

feat: add Nx.tile/2 function

---

torchx/c_src/torchx.cpp
torchx/lib/torchx/backend.ex
torchx/test/torchx/nx_doctest_test.exs

It gets shape mismatch exceptions on new `Nx.slice_axis` doctests.

Handle any scalars (integer or float) in NIFs

---

exla/bench/softmax.exs
exla/examples/mnist.exs

Without this change the examples are currently broken.

Add missing :compiler opts to Defn.aot calls

---

nx/lib/nx/binary_backend.ex

When concatenating along various axis we traverse bytes to order them properly, but that's not necessary for concatenating over axis 0. In such case all we have to do is to join the bytes.
Here's a benchmark for concatenating `Nx.iota({100, 100, 100}) |> Nx.to_batched_list(1)`:
<details>
<summary>Output</summary>
```
Operating System: Linux
CPU Information: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
Number of Available Cores: 4
Available memory: 30.80 GB
Elixir 1.12.0-dev
Erlang 23.0.3
Benchmark suite executing with the following configuration:
warmup: 2 s
time: 5 s
memory time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 14 s
Benchmarking Nx.concatenate...
Benchmarking Nx.concatenate before...
Name                            ips        average  deviation …
```

Optimise concatenate along axis 0

---

exla/lib/exla/defn.ex
exla/lib/exla/lib.ex
exla/test/exla/defn_expr_test.exs
nx/lib/nx.ex
nx/lib/nx/defn/expr.ex

This PR fixes the argument types for the sort comparator function so it can operate correctly on any input type + the iota for EXLA's argsort

fix: inherit input type in argsort

---

exla/c_src/exla/exla_nif_util.cc
exla/lib/exla/defn.ex
exla/test/exla/defn_expr_test.exs
nx/lib/nx.ex
nx/lib/nx/defn/grad.ex
nx/test/nx/defn_test.exs

Removes `dot/4` as well in favor of the general `dot/6` and supports `dot/6` in EXLA.

Add batching to EXLA dot product

---

nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs
nx/test/nx_test.exs

Adds batched dot product gradient. I also suggest we refactor `dot/6` to accept successive batch dimensions starting at 0, it's the same behavior as XLA. We can keep most of the logic, since the successive batch dimensions are basically squeezed, it just retains a different output shape

Add batch dot gradient

---

torchx/Makefile

Closes #368.
Suggestion/Proposal: Maybe we should also check whether the version installed is beyond the version supported by us (eg: we may not support a nightly version at some point of time). That's why I renamed `REQUIRED_*` to `MINIMUM_*`

LibTorch Makefile version check

---

exla/lib/exla/defn.ex
nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/expr.ex
nx/test/nx/defn/evaluator_test.exs
nx/test/nx_test.exs

Currently `argsort/2` doesn't work inside defn unless compiled with EXLA, because the expression is not compatible with BinaryBackend. This unifies the expression for both EXLA and BinaryBackend as @seanmor5 suggested.

Make argsort expr compatible with both BinaryBackend and EXLA

---

nx/lib/nx.ex

Closes #393.
Experimenting with @seanmor5 we found out that even with XLS stable sort, the results don't look stable at all (the order of same elements is reversed). Turns out the comparators need to be strict inequality, and in turn this fixes the segfault problem.

Change default sort comparators to use strict inequality

---

nx/lib/nx/lin_alg.ex
nx/test/nx/lin_alg_test.exs

I found a small thing when fooling around with Nx:
Trying to compute the p-norm of a zero vector raises an ArithmeticError.
```elixir
t = Nx.tensor([0,0,0])
Nx.LinAlg.norm(t, ord: 2)
** (ArithmeticError) bad argument in arithmetic expression
(nx 0.1.0-dev) lib/nx/binary_backend.ex:681: Nx.BinaryBackend.element_divide/3
(nx 0.1.0-dev) lib/nx/binary_backend.ex:639: Nx.BinaryBackend."-element_wise_bin_op/4-lbc$^17/2-9-"/7
(nx 0.1.0-dev) lib/nx/binary_backend.ex:638: Nx.BinaryBackend.element_wise_bin_op/4
(nx 0.1.0-dev) lib/nx/lin_alg.ex:264: Nx.LinAlg.norm_integer/3
```
EDIT: Actually it fails for tensors like `Nx.tensor([0, -2, -3, -1])` as well (0 is the maximum) because abs is not used when computing the stability coefficient.
There is this stabilization coefficient that is equal to the …

Fix p-norm throwing ArithmeticError for zero vectors

---

nx/lib/nx.ex

This is something I needed for personal use, so I figured I ought to make a PR since I have the implementation ready anyway.
I presume the `Nx.stack` function is supposed to deliver similar functionality as `np.stack` which supports stacking along any given axis - [numpy docs](https://numpy.org/doc/stable/reference/generated/numpy.stack.html#numpy-stack).  The current implementation from `main` works only along the first axis (the docs say it only works for scalar tensors, but in reality the implementation supports any rank).
I think this function is a bit lackluster if it doesn't support this. What do you think?

Make Nx.stack/2 support stacking along any axis

---

exla/lib/exla/defn.ex
exla/test/exla/defn_expr_test.exs
nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/expr.ex
nx/test/nx_test.exs

Replaces the `:comparator` option of `sort` and `argsort` with `:direction` that is either `:asc` or `:desc`. We decided not to allow arbitrary comparator functions, as some backends may not support it (Torchx) and Jax doesn't support that either.

Remove support for user-defined comparator for sort and argsort

---

nx/lib/nx/binary_backend/matrix.ex
nx/lib/nx/lin_alg.ex

Adds missing opts from [XLA](https://www.tensorflow.org/xla/operation_semantics#triangularsolve) to `Nx.LinAlg.triangular_solve`

feat: add more options to triangular_solve

---

nx/lib/nx/binary_backend/matrix.ex
nx/lib/nx/lin_alg.ex
nx/test/nx/lin_alg_test.exs

Solves #403 
As reported in said issue, some properties which held in XLA (and also hold in Jax) did not hold for the current implementation in Nx. Upon further inspection, besides some bugs, there was a conceptual error in the `:transform_a` option.
XLA, it interacts with `:lower` for defining the final interpretation of the matrix, and in my implementation, it was a non-informed transform which didn't change `:lower` in any way.

fix: use correct contracts for triangular_solve opts

---

nx/lib/nx/binary_backend/matrix.ex
nx/lib/nx/lin_alg.ex
nx/test/nx/defn/expr_test.exs

This PR aims to improve factorization results by applying
rounding over the `eps` parameter for each resulting component
Example:
```elixir
iex(1)> t = Nx.tensor([[10000, 2000, 3], [1, 2, 4], [1, 2, 5]])
#Nx.Tensor<
s64[3][3]
[
[10000, 2000, 3],
[1, 2, 4],
[1, 2, 5]
]
>
iex(2)> Nx.LinAlg.qr(t, eps: 1.0e-3)                           
{#Nx.Tensor<
f32[3][3]
[
[1.0, 0.0, 0.0],
[0.0, 0.7071067690849304, -0.7071067690849304],
[0.0, 0.7071067690849304, 0.7071067690849304]
]
>, #Nx.Tensor<
f32[3][3]
[
[1.0e4, 2000.0003662109375, 3.0009000301361084],
[0.0, 2.5455844402313232, 6.363536834716797],
[0.0, 0.0, 0.7071067690849304]
]
>}
iex(3)> Nx.LinAlg.qr(t)             
{#Nx.Tensor<
f32[3][3]
[
[1.0, -1.4142136205919087e-4, 0.0],
[9.999999747378752e-5, 0.7071067690849304, -0.7071067690849304], …
```

feat: apply eps to factorization results

---

exla/README.md

missing plural s for .tool-versions (asdf file) per https://asdf-vm.com/#/core-configuration?id=tool-versions

readme asdf correction: .tool-version -> .tool-versions

---

exla/c_src/exla/exla.cc
exla/lib/exla/defn.ex
exla/lib/exla/nif.ex
exla/lib/exla/op.ex
exla/test/exla/defn_expr_test.exs
nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/shape.ex

This PR introduces two bits:
* bindings to [`xla::Gather`](https://www.tensorflow.org/xla/operation_semantics#gather) - a very generic operation that may be used to implement many specific operations
* `Nx.take/3` - one specific operation backed by `xla::Gather`, it corresponds to [np.take](https://numpy.org/doc/stable/reference/generated/numpy.take.html) (Group 1 below). I went with the same naming because gather is too broad, but alternatives are welcome
Gather is a really broad term and its meaning varies across packages, some variants I found could be grouped like so:
**Group 1: "reorder" tensor along specific axis**
```
tensor: [
[1, 2],
[3, 4]
]
indices: [1, 0, 1]
result along axis 0: [
[3, 4]
[1, 2],
[3, 4]
]
```
* [tf.gather](https://www.tensorflow.org/api_docs/python/tf/gather) …

Implement Nx.take/3 backed by xla::Gather

---

exla/test/exla/defn_expr_test.exs
nx/lib/nx/binary_backend.ex
nx/lib/nx/binary_backend/matrix.ex
nx/lib/nx/shape.ex

Fixes the Nx.Shape rule for SVD, allowing for all kinds of matrices.
Some backends, like BinaryBackend, may raise depending on the implementation
limitations.
closes #444

fix: support wide matrices for backends other than the binary backend

---

nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/shape.ex
nx/test/nx/defn/stream_test.exs

This PR adds `Nx.take_along_axis/3`, which makes `Nx.argsort/3` more
useful, allows for more flexible indexing of tensors and
enables the grad implementation for `Nx.sort/2`

feat: add take_along_axis (with binary backend impl)

---

exla/mix.exs
exla/mix.lock

As long as we point `:xla` to GitHub it needs to be a specific version, so that we can build a new XLA release before it gets "public".

Point XLA to Hex

---

exla/lib/exla/defn.ex
exla/test/exla/defn_expr_test.exs
nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/shape.ex

Implements "Group 3" outlined in #433. Essentially this allows for building a new tensor from arbitrary individual elements from the original tensor.
As pointed out in #433, *gather* is not exactly an unambiguous term, but seems like the most appropriate name for this operation, especially that this should pair with how scatter works.

Implement gather

---

nx/lib/nx/binary_backend.ex

As mentioned in https://github.com/elixir-nx/nx/pull/456#issuecomment-921674991 this adjusts `take_along_axis` to also throw on invalid index.
Also, I extracted the index->offset into its own function, since it's the same for both gather and scatter add :)

Assert index in bounds in take_along_axis

---

exla/Makefile
torchx/Makefile

Currently, EXLA does not link on Mac OS. It cannot find the NIF symbols. There are [two known answers to this](https://stackoverflow.com/questions/8288358/erlang-nif-test-os-x-lion) which I tried. But both fail next with the following reason:
```
10:20:23.468 [warn]   The on_load function for module Elixir.EXLA.NIF returned:
{:error,
{:load_failed,
'Failed to load NIF library: \'dlopen(/Users/jose/OSS/nx/exla/_build/test/lib/exla/priv/libexla.so, 2): Library not loaded: bazel-out/darwin-opt/bin/tensorflow/compiler/xla/extension/libxla_extension.so\n  Referenced from: /Users/jose/OSS/nx/exla/priv/libexla.so\n  Reason: image not found\''}}
```
I am wondering, instead of linking to libxla_extension.so, could we instead build a fat binary with libxla_extension and simplify stuff like rpath …

Fix exla and libtorch for Mac OS

---

.github/workflows/ci.yml
exla/test/exla/defn_api_test.exs

See https://github.com/elixir-nx/nx/runs/3654704783#step:8:16, the error gets logged out, but the test already catches that error.

Ignore expected error log in tests

---

exla/README.md
exla/config/runtime.exs
exla/lib/exla.ex

Closes #197 
Also sets a lower `:memory_allocation` in runtime configuration so all tests can pass. The old default may cause issues with certain GPUs and CUDA versions which leads to CUDA OOM. The recommended default of 0.9 is still what JAX uses, but 0.8 is what I needed to set to get my GPU to pass all of our tests.

Add note on CUDA stack size and lower default memory allocation

---

nx/lib/nx/binary_backend.ex
nx/lib/nx/binary_backend/matrix.ex
nx/lib/nx/lin_alg.ex

This is an attempt to fix the `Nx.LinAlg.triangular_solve` BinaryBackend implementation, as reported on #473
closes #473

fix: handle tall/wide b matrix on tri solve

---

torchx/mix.exs
torchx/test/support/torchx_case.ex
torchx/test/test_helper.exs
torchx/test/torchx/backend_test.exs
torchx/test/torchx/nx_doctest_test.exs

Adds specific tests for some of the functions which don't have exactly the same output as on Nx.BinaryBackend (float rounding errors, different rounding strategies, etc)

test: add tests for rounding error doctests

---

nx/lib/nx.ex
nx/test/nx_test.exs
torchx/test/torchx/nx_doctest_test.exs

This PR adds `~M[]` sigil that evaluates to `#Nx.Tensor<>` as discussed in #358, but with type in the modifier.
I've added conditional compilation since support for digits in sigils was just merged to Elixir (elixir-lang/elixir#11283).

Add sigil for tensors

---

nx/lib/nx/binary_backend/matrix.ex

Removed unnecessary arguments and processing for the `hessenberg_decomposition` function that gets the Hessenberg form matrix. Details are below.
- Since the Hessenberg form matrix is a square matrix[[link](https://en.wikipedia.org/wiki/Hessenberg_matrix)], the arguments m and k are not necessary.
- In the case of a square matrix, `zero_padding` is `[]`, so it is not necessary.

Remove unnecessary code in the Hessenberg function

---

exla/lib/exla/defn.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/evaluator.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/grad.ex
nx/lib/nx/defn/kernel.ex
nx/lib/nx/defn/tree.ex
nx/test/nx/defn/expr_test.exs
nx/test/nx/defn/kernel_test.exs
nx/test/nx/defn/tree_test.exs
nx/test/nx/defn_test.exs
torchx/lib/torchx/backend.ex

Otherwise someone can write this code:
```elixir
defn example(matrix) do
{m, n} = Nx.shape(matrix)
if m == n do
...
else
...
end
end
```
And a boolean would be given to `if`, making it raise. Alternatively we could allow booleans in `if`, `and`, etc. But I don't think we should go down this slippery slope yet. :D

Return 0/1 from comparison operators in Kernel

---

exla/c_src/exla/exla.cc
exla/c_src/exla/exla_client.cc
exla/c_src/exla/exla_client.h
exla/c_src/exla/exla_nif_util.h
exla/test/exla/buffer_test.exs
exla/test/exla/defn/api_test.exs
exla/test/exla/device_backend_test.exs

We tagged the buffers as zero copy but the VM only
guarantees the binary won't be relocated during the
NIF call. So we set it to immutable until transfer
and block until ready.

Fix race condition on preloaded buffers

---

nx/lib/nx/defn/expr.ex
nx/test/nx/defn_test.exs

Also fixes a bug with the error message if the outputs are scalar values and shapes/types don't match

Add cond/if patch

---

nx/lib/nx/container.ex
nx/test/nx/container_test.exs
nx/test/nx/defn/evaluator_test.exs
nx/test/support/container.ex

This fixed a compilation error for me for "reset" values in containers

Use macro escape to work with empty map

---

nx/lib/nx.ex

This function helps quickly get the size of an axis.
Mentioned on stream by @josevalim.
This closes #575.
Modified slightly from issue to allow for negative index access.

Add Nx.axis_size

---

nx/lib/nx/lin_alg.ex
torchx/test/torchx/nx_linalg_doctest_test.exs

This PR implements the matrix_power function as requested in #582, using repeated squaring to calculate the power in logarithmic time.
Two doctests are provided, one to make sure that identity matrices don't change, and one to test a simple exponent case. This should be enoguh to catch serious implementation issues, and enough to provide documentation on what this function actually does.
Note that technically, if we were to ever support arbitrarily large numbers, this algorithm would take more in the neighborhood of linear time, as the multiplication of very large integers becomes slower with the width of such integers.

Implement Nx.LinAlg.dot_power/2 (#582)

---

torchx/Makefile

Allow users to use their own toolchain by setting env var "CMAKE_TOOLCHAIN_FILE". 
But I'm not sure if this is where you would like to put this empty CMake toolchain file (`torchx/toolchain.cmake`). If not, could you please suggest the best location for this file? Thanks!
Also, I had a thought that if we want to avoid adding an empty file, we can use
```
CMAKE_TOOLCHAIN_FILE ?= /dev/null
```
but that's probably not gonna work on systems that do not have a `/dev/null` (e.g., Windows), or its `/dev/null` behaves differently than what we would have expected.

Allow users to use their own toolchain

---

nx/lib/nx/heatmap.ex

The `to_heatmap` function causes exceptions by zero division when all the elements of the given tensor data are the same. In that case, the values of both `max` and `min` are the same so `base` becomes zero that will used as the divisor.
I made a quick hack to use 1 as the divisor instead of `base` to avoid zero-division. In this case, all the cell will be displayed as black. I use the integer 1 as the divisor because I expect the compiler might optimize to limit divide operations, but I am not sure about that.

to avoid divided by 0.0 when all the elements of the tensor data are the same value.

---

nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/tree.ex
nx/test/nx/defn/evaluator_test.exs

#587 
There's a case when an element_wise operation is appled to a number. Maybe it's ok to convert it to scalar just before the operation.

Add: elementwise ops for numbers + Fix: window_reduce + Fix: typo

---

exla/lib/exla/defn.ex
exla/test/exla/defn/api_test.exs

Currently the `device_id` configured in global defn options is ignored by EXLA.

Propagate device_id option to EXLA computation

---

exla/lib/exla/lib.ex
exla/test/exla/defn/expr_test.exs
nx/lib/nx.ex
nx/test/nx/defn/expr_test.exs

ONNX supports this option in argmin and argmax, and we support this for all other reductions, so I figured it made sense :)

Add keep_axis to argmin and argmax

---

nx/lib/nx.ex
nx/test/nx_test.exs

This PR adds some utility functions to NX.

add utility functions to NX

---

torchx/mix.exs
torchx/mix.lock

I've published the `:dll_loader_helper` library to hex.pm, and now we can use it as a hex package.

use :dll_loader_helper from hex.pm

---

torchx/README.md
torchx/mix.exs

Currently the `mix.exs` script downloads precompiled LibTorch binaries for `x86_64` on Apple M1-series Macs. This patch checks for the system architecture and adds instructions for downloading precompiled LibTorch for Apple M1-series with HomeBrew.

Added instructions for downloading precompiled libtorch for Apple M1

---

exla/Makefile

Close #511. Note that I did not investigate why `-isystem` fails instead!

EXLA: use -I flag instead of -isystem

---

nx/lib/nx.ex

We currently use `Nx.Shape.normalize_axis/3` a lot internally, but a similar functionality could be useful outside. Specifically, when writing custom generic functions that accept `:axis`, in order to validate shapes we may need the axis index to operate on shape tuples.

Add Nx.axis_index/2

---

nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/test/nx_test.exs

fix: do not re-sort contracting axes for generalized dot product

---

exla/examples/mnist.exs
exla/examples/regression.exs
exla/lib/exla.ex
exla/test/exla_test.exs

EXLA will have a fully functional backend in the future, so I thought we should rename the function to something more generic. We could even add a similar function to Torchx in the future.

Add EXLA.set_as_nx_default/2

---

torchx/c_src/torchx.cpp
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex
torchx/test/torchx/nx_doctest_test.exs
torchx/test/torchx/nx_test.exs

This PR is a major refactor upon the Torchx implementation for windowed functions. It's a little bit of a step back in the sense that dilations aren't supported anymore, ~but padding will be easier to implement now through `Torchx.pad`~ but padding is now supported through `Torchx.pad` and we get the basic implementations for `window_sum` and `window_product` working as well

feat(torchx): overhaul window functions (+ sum and product)

---

torchx/test/torchx/nx_test.exs
torchx/test/torchx_test.exs

fix the cases we still need the original variable. use _copy instead.

Fix test cases for backend_transfer

---

nx/lib/nx/defn.ex

Starting a line with a number followed by a period causes Markdown to format the line as a list.
Screenshot:

Avoid accidental Markdown list

---

nx/lib/nx.ex

Updates the behaviour to match [tf.random.shuffle](https://www.tensorflow.org/api_docs/python/tf/random/shuffle) and [np.random.shuffle](https://numpy.org/doc/stable/reference/random/generated/numpy.random.shuffle.html).
The behaviour with no `:axis` stays the same.

Change Nx.shuffle/2 along axis to keep order along other axis

---

nx/lib/nx/lin_alg.ex

closes #681 
It didn't calculate `parity` value properly.

Fix: Nx.LinAlg.determinant

---

nx/lib/nx/shape.ex
nx/test/nx/shape_test.exs

Previously, Nx.conv would fail silently if the convolution would result in zero-sized dimensions. This adds a shape check + error message

Fix conv zero-sized shape bug

---

torchx/test/torchx/nx_doctest_test.exs
torchx/test/torchx/nx_test.exs

This commit adds the make_diagonal doctests and a make_diagonal
nx test to the Torchx backend.
See #682.

Add make_diagonal tests for Torchx

---

torchx/test/support/torchx_case.ex
torchx/test/torchx/nx_test.exs

Introduce `assert_equal` to use when 2 tensors are expected to be exactly equal.
See https://github.com/elixir-nx/nx/pull/697#discussion_r8351958590.

Introduce assert_equal into Torchx.Case

---

exla/lib/exla.ex
exla/lib/exla/client.ex

This PR fixes the warnings passed by generating docs for EXLA.

Fix warnings in EXLA docs

---

nx/lib/nx/defn/grad.ex
nx/lib/nx/lin_alg.ex
nx/test/nx/defn/grad_test.exs

Reference taken from Jax:
```python
def _conj_transpose_rule(t, x, *, input_dtype):
assert ad.is_undefined_primal(x)
if dtypes.issubdtype(input_dtype, np.complexfloating):
return [conj(t)]
else:
return [real(t)]
```
real and imag grads were derived from the fact that they can be written as functions of conj, + and /
Also adds tests for most of #695

feat: add grads for conjugate,imag,real and validate complex functions

---

exla/bench/softmax.exs
exla/c_src/exla/exla.cc
exla/c_src/exla/exla_client.cc
exla/c_src/exla/exla_client.h
exla/lib/exla.ex
exla/lib/exla/backend.ex
exla/lib/exla/defn.ex
exla/lib/exla/defn/buffers.ex
exla/lib/exla/defn/stream.ex
exla/lib/exla/executable.ex
exla/lib/exla/nif.ex
exla/test/exla/defn/api_test.exs
exla/test/exla/defn/expr_test.exs
exla/test/exla/executable_test.exs
exla/test/exla/multi_device_test.exs
exla/test/support/exla_case.ex

Removes the `:keep_on_device` option and effectively makes it the default behaviour.
Context: the `EXLA.Backend` (#739) allows for using regular Nx operations on a device tensor, so implicit transfer to the CPU doesn't really sense.

Always keep data on the EXLA device after computation

---

exla/Makefile

Add a bazel path for darwin (Intel macs) to point to the correct file.
Closes #745

Fix cache pathing for intel macs

---

exla/lib/exla/defn.ex
exla/test/exla/defn/expr_test.exs

Closes #699.
When inside cond, we transform the branch `expr` here
https://github.com/elixir-nx/nx/blob/ee3ba17d5bc69cb0f782b5713c9055930f004439/exla/lib/exla/defn.ex#L1422-L1423
The transformation shifts the parameters as in [this diff](https://www.diffchecker.com/4C6XHPnE).
(I assume that's expected, but if not, maybe that's the actual issue)
---
Then we call `token_computation` for while pred and body, where we remap parameters from while `args`, such that they point to the while parameter tuple. This remapping ignores the position in existing parameter expressions, so if none of the parameters has position 0 it breaks.

Fix while inside cond

---

nx/mix.exs

Currently `[` `]` are classified as math delimiters:

Fix KaTeX initialization

---

nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

The main issue which was holding me back on this is that `jax.lax.linalg.cholesky` has a default option of `make_symmetric=True`, which adds a transform `input := (adjoint(input)+ input)/2` both at the beggining of the cholesky algorithm and at the end of the grad calculation (same transform but with the grad result instead).
I've kept a comment regarding this for when we want to support said option, if we end up doing it.

feat(complex/grad): support cholesky

---

nx/lib/nx/defn/kernel.ex
nx/test/nx/defn/kernel_test.exs

Adds the `div/2` to function to perform integer division to `Nx.Defn.Kernel`.
Closes #815.

Add `div/2` to `Nx.Defn.Kernel`

---

nx/lib/nx/backend.ex

The phase optional callback was not added to the `Nx.Backend` module.
Thus, when implementing the callback for a backend, warnings are
passed during compilation.
This commit fixes those warnings, by adding the callback as optional
in the `Nx.Backend` module

Fix warnings with implementing `Nx.phase` as an optional callback

---

nx/lib/nx.ex
nx/lib/nx/defn/composite.ex
nx/lib/nx/defn/kernel.ex
nx/lib/nx/shared.ex
nx/lib/nx/type.ex
nx/test/nx/defn_test.exs
torchx/.formatter.exs

This PR adds support for booleans as tensor inputs (true -> 1, false -> 0),
which means that:
- We now support literal true and false being used as explicit tensor constants (i.e. `Nx.tensor(true)`)
~- Booleans are now valid inputs for defn and for Nx functions~
- logical and comparison expressions also work accordingly with booleans

feat(defn): support booleans

---

torchx/lib/torchx/backend.ex
torchx/test/torchx/nx_doctest_test.exs

Taking inspiration from the Pytorch JIT implementation for bitcast, this PR enables bitcast by copying the raw blob into the "wrong" output type.
https://github.com/pytorch/pytorch/blob/0f6b524665378b18b8682f473267c80c6d5ca3df/torch/csrc/jit/tensorexpr/cpp_intrinsics.h#L27
closes #848

feat(torchx): bitcast

---

torchx/README.md

Given that Torchx is now released in Hex, the specification to use Git is not needed any more.

Remove the mention of adding Torchx using Git as it is now in Hex

---

torchx/test/torchx/nx_test.exs

Add tests for dot in `torchx/test/nx_test.exs` given that the doctests are disabled due batching not being supported.
Issue #682

Add tests for dot on torchx

---

torchx/test/torchx/nx_test.exs

Adding `Nx.mean/2` tests for Torchx. These tests are added as part of the tests since the doctests are skipped given that Torchx does not support unsigned integers.
Issue #682

Add mean tests for Torchx

---

torchx/test/torchx/nx_doctest_test.exs
torchx/test/torchx/nx_test.exs

Added tests for `Nx.quotient/2` since the doctests are ignored due to unsigned integers not being supported on Torchx.
`argmax` and `argmin` doctests no longer use complex numbers, which allows them to be restored.
Related to issue #682

Add quotient test for Torchx. Remove argmax and argmin from exclusion list.

---

torchx/test/torchx/nx_test.exs

Broadcast is the last one of the functions that are skipped in the doctests and are missing from the tests. With these changes, I think issue  #682 could be closed as the sigil functions are actually tested via the doctests (unless the idea is to use the same issue to track the changes that will allow to restore doctests).

Add broadcast tests for Torchx

---

nx/lib/nx/binary_backend.ex
nx/lib/nx/lin_alg.ex
nx/lib/nx/shape.ex
nx/test/nx/lin_alg_test.exs

Makes `Nx.LinAlg.qr` work with batched tensors. 
When given batched tensor `Nx.LinAlg.qr` will perform QR decomposition across the matrices in inner-most 2 dimensions, keeping the rest of the shape unaffected.

Support batched tensors in `Nx.LinAlg.qr`

---

nx/guides/intro-to-nx.livemd

I think what that sentence is meant to say is
> `defn` is a subset of the language allowed in the `def` block.

Fix typo in intro-to-nx

---

nx/lib/nx/shape.ex

The message when using `defn` with integer argument causes ArgumentError, but the message is incorrect:  
```elixir
** (ArgumentError) invalid dimension in axis 0 found in shape. Each dimension must be a positive integer, but instead got a tensor as dimension: #Nx.Tensor<
s64
Nx.Defn.Expr
parameter a:0   s64
>
This may happen if you are trying to pass a dimension or a shape as an argument to a defn function, for example:
defn my_defn(dim) do
Nx.iota({dim})
end
However, defn treats all arguments as inputs. To address this, you can pass the dimension or the shape as an option instead:
defn my_defn(opts \ []) do
opts = keyword(opts, dim: 1)
Nx.iota({opts[:dim]})
end
Invalid shape: {#Nx.Tensor<
s64
Nx.Defn.Expr
parameter a:0   s64
>}
```
This PR corrects it as follows:
```elixir
** …
```

Fix the issue of my_defn

---

nx/lib/nx/binary_backend.ex
nx/lib/nx/lin_alg.ex
nx/lib/nx/shape.ex
nx/test/nx/lin_alg_test.exs
torchx/lib/torchx/backend.ex

Batched tensors support for:
- `Nx.LinAlg.eigh`
- `Nx.LinAlg.invert`
- `Nx.LinAlg.solve`
- `Nx.LinAlg.triangular_solve`

Support batched tensors in another part of `Nx.LinAlg` functions 

---

torchx/lib/torchx/backend.ex
torchx/test/torchx/nx_test.exs

Part of the bugs caught by Axon
1. conv output_permutations were in disagreement with Nx.Shape
2. binary ops didn't broadcast args properly

fix: compatibilize shape in some operations

---

torchx/lib/torchx/backend.ex
torchx/test/torchx/nx_test.exs
torchx/test/torchx_test.exs

closes #895
This is an edge case which I wasn't able to reproduce through normal Nx APIs.
Some torch functions return a bool-typed tensor instead of byte-typed for u8.
This leads to some unexpected behavior which was mostly hidden under an upcast we had specifically for u8 -> s16.
This PR converts all bool underlying tensors to byte tensors when returning to Nx-land

fix(torchx): avoid returning bool type in underlying tensors

---

nx/lib/nx/lin_alg.ex

In a minor fix, [the value 1.0e-10 defined in `@default_eps`](https://github.com/elixir-nx/nx/blob/c01b2302620e51af212d752e83712af95860bf51/nx/lib/nx/lin_alg.ex#L12) was different from the value 1.0e-12 in the doc comment, so the comment was fixed.

Minor fix the svd function's comment for eps

---

nx/lib/nx.ex
nx/lib/nx/lin_alg.ex
nx/lib/nx/shape.ex
nx/test/nx/lin_alg_test.exs
nx/test/nx_test.exs

Batched tensors support for:
- `Nx.LinAlg.determinant`
- `Nx.LinAlg.matrix_power`
- `Nx.take_diagonal`

Support batched tensors in `determinant/1`, `matrix_power/2`, and `take_diagonal/2`

---

torchx/lib/torchx/backend.ex
torchx/test/torchx/nx_test.exs
torchx/test/torchx/random_test.exs
torchx/test/torchx_test.exs

This aligns the random values between torchx and the binary backend.

Emulate remainder for all u64 integers

---

nx/lib/nx.ex
nx/lib/nx/shared.ex

This PR fixes wrong Latex delimiters in docs about `Nx.phase/1`, `Nx.conjugate/1`, `Nx.log/1`.

Fix wrong Latex delimiters in docs

---

nx/lib/nx/defn/expr.ex
nx/test/nx/defn_test.exs

Currently jitting a while with generator (and no unroll) fails with EXLA, because the generator-specific params are not included as while arguments.

Include generator parameters in the while expression node

---

.github/workflows/ci.yml

This commit fixes dependency caching by doing the following:
- Upgrading from cache@v1 to cache@v3
- Using a more verbose cache path
- Changing the key format to be a bit more clearer
Caching attempts were failing as result of an invalid path, which did not account for the change in working directory.
By using a more verbose path, this issue has been eliminated.
Closes #867

Fix dependency caching in CI

---

nx/lib/nx/random.ex

We know the counts are even,
so we can skip padding and reshaping.

Reduce Nx.Random.split tree

---

exla/test/exla/backend_test.exs
exla/test/exla/defn/expr_test.exs
nx/lib/nx/defn.ex
nx/lib/nx/defn/compiler.ex
nx/lib/nx/defn/composite.ex
nx/lib/nx/lazy_container.ex
nx/test/nx/defn/grad_test.exs
nx/test/nx/defn_test.exs
nx/test/nx_test.exs

Prior to this patch, `compile`/`jit` accepted only tensors while `defn` allowed functions and keyword lists as default arguments.
This PR unifies the approaches such that functions and lists are allowed in all APIs, regardless if a default argument or not.
This simplifies the implementation and makes the
process of compiling/jitting a `defn` simpler.

Unify defn arguments

---

exla/lib/exla/defn.ex
exla/mix.exs
nx/lib/nx.ex

Currently `:keep_axes` fails, because we always try to reshape to a scalar.

Fix Nx.{any,all} with :keep_axes on EXLA

---

exla/lib/exla.ex
exla/lib/exla/defn.ex
exla/mix.exs
exla/mix.lock
exla/test/exla/defn/api_test.exs

This commit adds telemetry events that are executed when EXLA compiles a function into an executable.
These events can be used to have observability into how many times functions are compiled and how long compiling them takes.
When a function is compiled, an event with name `[:exla, :compilation]`
is executed. The measurements include the following:
- `eval_time` - time it took to call the defn function that is compiled
- `compile_time` - time it took for XLA to compile the instructions into
an executable
- `total_time` - sum of `eval_time` and `compile_time`
This commit is related to the issue
https://github.com/elixir-nx/nx/issues/974

feat: send telemetry event after XLA compilation

---

nx/lib/nx.ex
nx/test/nx/defn_test.exs
nx/test/nx_test.exs

Ensures that the returned tensor has the same precision for its real and imaginary parts as the lowest precision input by checking precision of inputs, and passing the correct type (`:c64` or `:c128`) to `Nx.Constants.i/1`.
Closes #979

No loss of precision in `Nx.complex/2`

---

nx/lib/nx/binary_backend.ex
nx/lib/nx/type.ex
nx/test/nx_test.exs

Because complex types are considered floats by `Nx.Type.float?/1` the binary backend's implementation of as_type does not preserve the imaginary part of a complex number when casting between :c64 and :c128.
This addresses that error by introducing a new function `Nx.Type.complex?/1` that is used to determine if the output of `as_type/1` should include just the real part of the input.
I considered modifying `Nx.Type.float?/1` to return `false` for complex types. This seems reasonable given the docs which say "is a float in elixir" and complex is a struct. However, this change produces a substantial number of errors in other tests. In the interest of keeping changes to a minimum, I added the `complex?` function and modified the binary backend's `as_type` implementation to check whether the …

Differentiate between complex and real output in binary backend `as_type`

---

exla/c_src/exla/exla.cc

For large computations the compilation may take a long time.

Mark EXLA compile as CPU bound

---

exla/c_src/exla/exla.cc
exla/c_src/exla/exla_client.cc
exla/c_src/exla/exla_client.h
exla/test/exla_test.exs
exla/test/test_helper.exs

Currently EXLA OOMs in special cases on the GPU because of a memory leak, this fixes that issue

Refactor EXLA execution and fix a memory leak

---

nx/lib/nx.ex

The [documentation](https://github.com/elixir-nx/nx/blob/main/nx/lib/nx.ex#L51-L74) has two code snippets in a row that are the same:
```elixir
Nx.tensor([1, 2, 3], type: :f32)
#Nx.Tensor<
f32[3]
[1.0, 2.0, 3.0]
>
```
The first snippet should read
```elixir
Nx.tensor([1, 2, 3], type: {:f, 32})
#Nx.Tensor<
f32[3]
[1.0, 2.0, 3.0]
>
```
because the second is intended to highly the "shortcut atom notation." If both snippets use the shortcut there is no contrast.

Fix shortcut atom notation example

---

nx/lib/nx/defn/tree.ex
nx/test/nx/defn/tree_test.exs

Before this patch, EXLA would compute `foo` or subtrees of `foo` twice:
if foo do
foo + 1
else
...
end
This is particularly troublesome for code like this:
{tree, flag} =
while do
...
end
if flag do
tree
else
...
end
Causing while to be evaluated twice.

Consider the first conditional of a cond part of the scope

---

.github/workflows/ci.yml

Apparently there's some strange relationship between the windows version of runner and the vs build tools version.
this [issue](https://github.com/SCons/scons/issues/3664) helps me to figure out what version is necessary to use

fix windows build

---

nx/config/config.exs
nx/lib/nx/binary_backend.ex

The new check for byte_size revealed the bug with BinaryBackend's pad.
I've made it so the check is only compiled for Nx development.

fix(BinaryBackend): pad

---

nx/lib/nx.ex
nx/lib/nx/defn.ex

Hey 👋 
this tiny PR is the follow-up on this comment https://github.com/elixir-nx/axon/issues/416#issuecomment-1346634166
It updates the docs for `Nx.default_backend/1`, `Nx.Defn.default_options/1` and their corresponding "global" version to highlight that the returned value is the one that was previously set (and not the updated one).
Plus, I added a doctest for the `Nx.Defn.default_options/1` analogously to the one in the `Nx.default_backend/1` docs.
Let me know if it is clear enough or if I can improve anything.
To conclude, I don't know if you follow any specific convention regarding PR titles, commits, etc. so feel free to change everything  as you wish :)
You are great!
Best,
Nicolò

docs(nx): specify return values for stateful operations

---

exla/lib/exla/backend.ex

Given
```elixir
Mix.install(
[
{:nx, path: "~/git/nx/nx", override: true},
{:exla, path: "~/git/nx/exla", override: true}
],
config: [
exla: [
clients: [
host1: [platform: :host],
host2: [platform: :host]
],
preferred_clients: [:host2]
]
]
)
Nx.default_backend({EXLA.Backend, client: :host1})
```
This gets allocated on `:host1` as expected, because we respect the default backend and options:
```elixir
Nx.tensor([1])
```
However, this gets allocated on `:host2`:
```elixir
Nx.iota({10})
```
Because we fallback to `EXLA.Client.default_name()` when jitting. This PR changes it such that we respect the default backend options instead.

Respect default EXLA.Backend client when jitting argumentless operations

---

nx/lib/nx/defn/compiler.ex
nx/test/nx/defn_test.exs

Having multi-arity functions in which some arities had various clauses previously
caused the compiler to emit "previous clause always matches" errors

fix: avoid re-declaring same arity transforms

---

exla/mix.exs

Currently, every variation of Mix.install/2 has to compile EXLA from scratch. This PR builds a cache for the operating system, ensuring a given elixir-erlang-xla-exla is only compiled once.
@jonatanklosko please let me know if you find any issues with the cache key.

Cache libexla.so across builds

---

nx/lib/nx/serving.ex
nx/mix.exs
nx/mix.lock
nx/test/nx/serving_test.exs

This begins by adding `telemetry` as an Nx dependency and wraps Serving's internal `batched_run` handler in a span. The span's meta includes simple statistics like queue depth, batch size limits, and other identification.
A few questions:
1. Is there any additional meta that would be helpful? The server's pid? The full stack?
2. Would you prefer a dedicated test for telemetry or include telemetry assertions in more of the server tests?
Once we've nailed this down, I'll move on to client-ide telemetry.
Addresses #1005

Add telemetry to Nx.Serving

---

exla/README.md

This hint is probably obsolete by now.

docs(exla): removed hint that you still need to use a Git Dependency

---

nx/lib/nx/lin_alg.ex
nx/lib/nx/shape.ex

The `matrix_rank` function is added that has the same function as [numpy.linalg.matrix_rank](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html).
This function returns matrix rank of input M × N matrix using Singular Value Decomposition (SVD) method.
- [Document of `numpy.linalg.matrix_rank`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html)
- Mathematical resources, for example,[ this document from Berkeley University (Proposition 1.3.)](https://math.berkeley.edu/~hutching/teach/54-2017/svd-notes.pdf) 
I ran the same test on `numpy.linalg.matrix_rank` as doctest and confirmed that the same results were obtained.

feat: matrix_rank

---

exla/Makefile
torchx/Makefile
torchx/mix.exs

Uses the same idea as in #1067, but doesn't create symlink if the Torch location was set in the `LIBTORCH_DIR` env.

TorchX - Use symbolic link to library if ENV is not set

---

nx/lib/nx/serving.ex
nx/test/nx/serving_test.exs

The goal is to allow us to device partitioning
in the future that will work transparently.
For example, we could do:
{Nx.Serving,
serving: my_serving(),
partitioned: true}
And, if you have two devices, it will create two
Nx.Serving and automatically partition the load
between them. This will be handy with the distributed
option too, making sure we can spread the load across
multiple GPUs and machines.

Make serving explicitly receive compiler options

---

nx/lib/nx/constants.ex
nx/lib/nx/type.ex
nx/mix.exs

Closes #1092 
Except mathematical constants, this PR also adds math notation in docs with the same configuration as in Axon.

Add fundamental mathematical constants

---

nx/lib/nx.ex

Currently, to create a tensor from a nested list is pretty easy with `Nx.tensor/1`, but the reverse operation can be a little complicated/frustrating.
There are a few options, such as `to_batched/3` and `to_flat_list/2`, but the problem with them is that additional steps are needed to get a nested list that represents the tensor structure back.
For example: https://elixirforum.com/t/converting-tensor-into-nested-list/44352
Because of that, some libraries end up creating their own `to_list` function to solve this, such as [Bumblebee](https://github.com/elixir-nx/bumblebee/blob/v0.1.2/lib/bumblebee/utils/nx.ex#L31) (where I got the code from).
This PR allows for this:
```elixir
iex> [[1, 2], [3, 4]] |> Nx.tensor() |> Nx.to_list()    
[[1, 2], [3, 4]]
```
This probably have already crossed …

Adds `to_list/1` to Nx

---

nx/lib/nx/lin_alg.ex

When a matrix with complex numbers as elements is entered into `matrix_rank` function, the error comment `"Nx.LinAlg.svd/2 is not yet implemented for complex inputs"` is displayed as below.  
Therefore, I corrected it so that the error comment `"Nx.LinAlg.matrix_rank/2 is not yet implemented for complex inputs"` is displayed.

Fix ArgumentError for complex case in matrix_rank function

---

torchx/mix.exs

Solved by: https://github.com/mlverse/libtorch-mac-m1/issues/2

chore: download precompiled libtorch 2.0.0 for mac arm

---

nx/lib/nx.ex
nx/lib/nx/lin_alg.ex

Vectorizes all of the non-defn functions in Nx.LinAlg with the exception of:
`norm`: one of the inner implementations uses `select/3`, which still needs vectorization
`svd`: The default implementation uses `dot`, which still needs to be vectorized properly.
Also adds more functionality to `Nx.vectorize` so that it can act as an inverse function of `Nx.devectorize` with ease

feat: vectorize (most of) Nx.LinAlg

---

nx/lib/nx.ex
nx/test/nx_test.exs

also simplifies some of the implementation for reshape_/broadcast_vectors

feat: vectorize concatenate

---

nx/lib/nx/defn/compiler.ex

This happens when building with `parser_options: [columns: true]`
Originally reported in https://github.com/elixir-lsp/elixir-ls/issues/864

Do not crash when meta is different on struct compile

---

nx/lib/nx/binary_backend.ex
nx/test/nx_test.exs

fix: reduce_min/max for non-finite values

---

nx/lib/nx.ex
torchx/lib/torchx/backend.ex

closes #1192
This basically replicates the algorithm for take-over-gather used in Torchx, so that we extend the still-vectorized indices to be passed onto the vectorized gather implementation.
Implementing directly over take would imply lots of really weird slicing and wouldn't yield much memory footprint improvement over what we have now.

fix: vectorized Nx.take

---

nx/lib/nx.ex
nx/mix.exs
nx/test/nx_test.exs

Adds another utility function for vectorized axes manipulation.
This solves the problem of collapsing and re-expanding vectorized axes.

feat: Nx.revectorize

---

exla/test/exla/defn/vectorize_test.exs
nx/lib/nx/tensor.ex
nx/test/nx/vectorize_test.exs

This also adds sanity tests to EXLA and 1 skipped test that
shows that we still need to support vectorized indices in Access.Nx.Tensor

fix: access on vectorized tensor with unvectorized indices

---

nx/lib/nx.ex
nx/test/nx_test.exs

A fix for this issue:
https://github.com/elixir-nx/nx/issues/1222
Thanks!
-- Greg

Fix Nx.linspace/3 so that it returns elements with proper :f64 precision

---

nx/lib/nx/lin_alg.ex

Minor correction to the comment statement for function `Nx.LinAlg.norm`.

Fix comment for the default `:ord` value of `Nx.LinAlg.norm`

---

nx/lib/nx.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/lin_alg.ex
nx/lib/nx/lin_alg/svd.ex
nx/test/nx_test.exs

While writing some vectorized code as an user I noticed
that it was far more common to want the align_ranks option
to be false. Also I found it confusing to see an axis pop
up out of nowhere 'til I remembered align_ranks existed.
We can also see this in Nx.LinAlg

refactor: change default for :align_ranks

---

nx/.gitignore
nx/lib/nx.ex
nx/test/nx_test.exs

based on this: https://github.com/elixir-nx/scholar/pull/107

add split function

---

exla/test/exla/random_test.exs
nx/lib/nx/random.ex

Right now if you use EXLA as the backend, using randint can sometimes return negative numbers even with a range like 0 -> 100
```elixir
Nx.default_backend(EXLA.Backend)
key = Nx.Random.key(127)
{randint, _new_key} = Nx.Random.randint(key, 0, 100, shape: {10})
randint
```
```
tensor: #Nx.Tensor<
s64[10]
EXLA.Backend<host:0, 0.2110671721.1027997711.177152>
[-14, 13, -10, -11, -72, -68, 9, -37, 96, -39]
>
```
But if you use the BinaryBackend, then it's fine
```elixir
Nx.default_backend(Nx.BinaryBackend)
key = Nx.Random.key(127)
{randint, new_key} = Nx.Random.randint(key, 0, 100, shape: {10})
randint
```
```
tensor: #Nx.Tensor<
u64[10]
[42, 13, 62, 61, 0, 4, 25, 35, 12, 33]
>
```
In the beginning of the randint algorithm, it creates some random bits and a span variable. If there's no …

fix: randint producing numbers outside min,max range

---

nx/lib/nx.ex

In this format, the tensor metadata including its
binary offset and size are stored upfront with all
binaries at the end. This can allow us, in the future,
to deserialize using mmap or without reading all file
upfront.
Closes #1186.

Provide new serialization format

---

nx/lib/nx/defn/expr.ex
nx/test/nx/defn/expr_test.exs

Adds pruning of in-between expressions so that we
it's easier to analyze the overall behavior of a Nx.Defn.Expr

feat: prune tensor expr inspect results

---

nx/lib/nx.ex

There is already an h2 Examples heading

Remove extraneous title in Nx.broadcast docs

---

nx/lib/nx/serving.ex
nx/test/nx/serving_test.exs

This adds a simple weight option to `Nx.Serving` that is factored into how many times the serving joins the process group, similar to `partition_count`, thereby making the randomized load balancing weighted.
Addresses https://github.com/elixir-nx/nx/issues/1346, at least in regard to static load balancing.

Add weight option to Nx.Serving for static load balancing

---

torchx/c_src/torchx.cpp
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex

- wip: torchx put slice
- fix: return outer ref

refactor(torchx): more efficient put_slice

---

nx/guides/intro-to-nx.livemd

The `tensor` should be `{2, 2}`.

Fixes the reshape example in intro Livebook.

---

nx/exercises/exercises-1-20.livemd
nx/mix.exs

As discussed in [Slack](https://the-eef.slack.com/archives/C01PU0RDJ8L/p1699644171094749), this PR adds a translation of the first 20 exercises from the Python notebook _100 Numpy Exercises_:
https://www.kaggle.com/code/utsav15/100-numpy-exercises/notebook
* Adds `exercises-1-20.livemd` file
* Tweaks the doc grouping in `mix.exs`
* Most of these first 20 translate 1-1. There were a few that didn't. I left comments (which we'll want to remove before merging).
* Going forward, not all of the exercises are going to make sense for Nx. This is (hopefully) more a jumping off point for community-curated exercises.

Exercises 1-20

---

nx/lib/nx/serving.ex

Hello, i was reading the `Nx.Serving` docs and notice the private function,  i guess should be a public function the `MyDefn.print_and_multiply/1`.
before
after

docs: fix first nx serving example

---

exla/c_src/exla/exla.cc
exla/c_src/exla/exla_client.cc
exla/c_src/exla/exla_client.h
exla/lib/exla/executable.ex
exla/lib/exla/nif.ex

To make cold starts faster we can save JIT compiled functions to disk. This should help FLAME cold starts.
Not sure what the API should look like for Nx as this may not work across backends/compilers. Maybe `Nx.Defn.load/save` ?

Add executable serialization

---

nx/lib/nx/constants.ex

Fixes a small error in the documentation of `Nx.Constants.smallest_positive_normal/2`.

Fix `Nx.Constants.smallest_positive_normal/2` documentation

---

exla/lib/exla.ex
exla/lib/exla/defn.ex
nx/lib/nx/defn.ex
nx/lib/nx/defn/compiler.ex
nx/lib/nx/defn/debug.ex
nx/lib/nx/defn/evaluator.ex

Partitioned servings receive defn options with respective device id and we may want to copy model params to each partitioned device. So far we've been doing `Nx.Defn.jit_apply(&Function.identity/1, [params], defn_options)`, however for EXLA this requires twice the params memory, because input and output use separate buffers.
This PR adds a function to infer backend from compiler options:
```elixir
Nx.Defn.Compiler.to_backend(compiler: EXLA, device_id: 1)
```

Add Nx.Defn.Compiler.to_backend/1

---

nx/lib/nx/binary_backend/matrix.ex
nx/test/nx/lin_alg_test.exs

bugfix: Nx.BinaryBackend.Matrix.ts/8 returns corrupted matrix when b has more columns than rows

---

exla/test/exla/mlir/nx_linalg_doctest_test.exs
nx/lib/nx/lin_alg.ex
nx/test/nx/lin_alg_test.exs
torchx/test/torchx/nx_linalg_doctest_test.exs

Added the `least_squares` function to obtain the solution of equation `Ax = y` by the least-squares method.
This function performs the same process as `numpy.linalg.lstsq` ([link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html)) to obtain the approximate values `x`.
As shown in example of `numpy.linalg.lstsq` ([link](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html#:~:text=returned%20as%20matrices.-,Examples,-Fit%20a%20line)) , it is possible to obtain a solution for extrapolation that can successfully fit multiple point data.
I have already confirmed that the solution of `numpy.linalg.lstsq` is almost the same value as the solution of this `Nx.LinAlg.least_squares`'s doctests.
[1] …

Add `least_squares` function

---

nx/lib/nx.ex

Very much a subject to comments.
Let's say we want to create a zeroed tensor, shape-compatible with `tensor`. We can do this:
```elixir
Nx.tensor(0, type: Nx.type(tensor)) |> Nx.broadcast(Nx.shape(tensor))
```
We could make this `Nx.full(shape, value, type: type)`, but I am not sure it has enough value.
However, if we want to create a zeroed tensor to exactly match `tensor`, including names and vectorized axes, then it becomes much more cumbersome:
```elixir
[zeros, _] =
Nx.broadcast_vectors([
Nx.tensor(0, type: Nx.type(tensor)) |> Nx.broadcast(Nx.shape(tensor), names: Nx.names(tensor)),
sample_template
])
Nx.tensor(0, type: Nx.type(tensor))
|> Nx.broadcast(Nx.shape(Nx.devectorize(tensor)), names: Nx.names(tensor))
|> Nx.vectorize(sample_template.vectorized_axes)
```
To make it clear that …

Add Nx.fill/2

---

exla/lib/exla/defn.ex
exla/lib/exla/mlir/value.ex
exla/lib/exla/op.ex
exla/test/exla/mlir/executable_feed_test.exs

Currently we infer `%Function{}` from tuple arguments, but if we want to build empty tuple, there are none. And we even build such explicitly here:
https://github.com/elixir-nx/nx/blob/c5d91781b91f63cae4917e75e0dc77507852e608/exla/lib/exla/defn.ex#L721

Fix building empty MLIR tuples

---

nx/lib/nx/defn/kernel.ex
nx/test/nx/defn/evaluator_test.exs

When debugging large intermediate tensors, I usually look at a small slice or summaries such as `Nx.sum`, however `print_value` requires the returned expression to be used as is. This always leads me to tricks such as:
```elixir
x
|> then(fn x -> x + 0 * Nx.sum(print_value(x[[.., 1..3]])) end)
```
I've just realised we can generalize `print_value` to support additional transformation by using `hook_token`. With the new version, the example above would be:
```elixir
x
|> print_value(& &1[[.., 1..3]])
```

Support a mapping function in Nx.Defn.Kernel.print_value/2

---

exla/c_src/exla/mlir/builder.cc
exla/lib/exla/builder.ex
exla/lib/exla/defn.ex
exla/lib/exla/defn/outfeed.ex
exla/lib/exla/lib.ex
exla/lib/exla/mlir/value.ex
exla/test/exla/backend_test.exs
exla/test/exla/defn/api_test.exs
exla/test/exla/defn/expr_test.exs
exla/test/exla/defn/vectorize_test.exs
exla/test/exla/mlir/executable_feed_test.exs
exla/test/exla/serving_test.exs
exla/test/test_helper.exs

Adds initial support for infeed and outfeed in MLIR
Some tests are still skipped due to incomplete/incorrect implementations
Also changes binary ops to receive an explicit builder function instead of requiring both operands to belong in the same function.

feat(mlir): initial infeed/outfeed support

---

exla/c_src/exla/exla.cc
exla/c_src/exla/mlir/builder.cc
exla/c_src/exla/mlir/builder.h
exla/c_src/exla/mlir/ops.cc
exla/c_src/exla/mlir/ops.h
exla/lib/exla/builder.ex
exla/lib/exla/computation.ex
exla/lib/exla/defn.ex
exla/lib/exla/executable.ex
exla/lib/exla/lib.ex
exla/lib/exla/mlir/value.ex
exla/test/exla/builder_test.exs
exla/test/exla/op_test.exs
exla/test/support/exla_helpers.ex

- refactor: new compilation for cond
- refactor: while on new workflow
- refactor: token computation
- refactor: sort computation
- refactor: op computation
- refactor: fun_computation
- refactor: stream computation
- refactor: root builder
- refactor: separate builder new fully
- refactor: remove mlir_build NIF

refactor(mlir): reduce tuple usage for returns in favor of variadic+flat tuples

---

exla/lib/exla.ex
exla/lib/exla/defn.ex

- feat: add compiler mode config
- feat: add compiler_mode config

feat: add config for compiler mode

---

exla/Makefile
exla/c_src/exla/exla.cc
exla/c_src/exla/mlir/builder.cc
exla/c_src/exla/mlir/builder.h
exla/c_src/exla/mlir/custom_calls.cc
exla/c_src/exla/mlir/custom_calls.h
exla/c_src/exla/mlir/ops.cc
exla/c_src/exla/mlir/ops.h
exla/lib/exla/defn.ex
exla/lib/exla/mlir/value.ex
exla/lib/exla/nif.ex
exla/test/exla/defn/expr_test.exs
exla/test/exla/executable_test.exs
exla/test/exla/mlir/custom_call_test.exs
exla/test/test_helper.exs

In short, during our migration to MLIR, QR got slower due
to being implemented in defn (which can't leverage things like in-place modifications).
This adds a custom call for using Eigen (which is already a dependency of ours) on the CPU.

feat(mlir): QR as custom call

---

exla/c_src/exla/exla.cc
exla/c_src/exla/mlir/ops.cc
exla/c_src/exla/mlir/ops.h
exla/lib/exla/defn.ex
exla/lib/exla/defn/outfeed.ex
exla/lib/exla/lib.ex
exla/lib/exla/mlir/value.ex
exla/lib/exla/nif.ex
exla/test/exla/backend_test.exs
exla/test/exla/executable_test.exs
exla/test/support/exla_case.ex
exla/test/support/exla_helpers.ex
exla/test/test_helper.exs

Removes tuples from EXLA altogether, as the MLIR compiler can work with variadic/lists of inputs and outputs

refactor: remove tuples from EXLA

---

exla/Makefile
exla/c_src/exla/exla.cc
exla/c_src/exla/exla_client.cc
exla/c_src/exla/exla_nif_util.cc
exla/lib/exla/defn/stream.ex
exla/lib/exla/executable.ex
exla/lib/exla/nif.ex
exla/lib/exla/shape.ex
exla/test/exla/executable_test.exs
exla/test/exla/shape_test.exs
exla/test/support/exla_helpers.ex

As far as I understand we no longer use it anywhere, as of #1463.

Remove all handling of EXLA.Shape tuple

---

exla/c_src/exla/exla_mlir.cc
exla/c_src/exla/exla_mlir.h
exla/lib/exla/mlir/value.ex

- chore: bubble ParseAttribute error up
- chore: mention device in exception

chore: bubble attribute error up

---

exla/lib/exla/backend.ex
exla/lib/exla/defn.ex
nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/evaluator.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/grad.ex
nx/lib/nx/defn/tree.ex
nx/lib/nx/shape.ex
torchx/lib/torchx/backend.ex

Generally speaking we want to reduce the number of callbacks but stack causes one additional copy of every tensor and it is used very frequently.
One option is to use optional callbacks, but concatenate/stack are the only operations that require a variable number of arguments, which is hard to include as part of the optional/evaluator system, so it its own callback.
Closes #1441.

Add stack as a callback

---

exla/lib/exla/defn.ex

We now check if the token will be needed, and only create if so. In places that pass the token through (optional computation, while, ...), we now do so conditionally.

Create HLO token in the computation only when needed

---

exla/lib/exla/lib.ex
exla/lib/exla/mlir/value.ex
nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/test/nx_test.exs

Currently the behaviour of argmax/min for NaNs is inconsistent with reduce_max/min:
```elixir
iex> Nx.reduce_max(Nx.tensor([1.0, :nan, 2.0]))
#Nx.Tensor<
f32
NaN
>
iex> Nx.argmax(Nx.tensor([1.0, :nan, 2.0]))
#Nx.Tensor<
s64
2
>
```
This is the case both for EXLA and BinaryBackend. I changed both such that argmax/argmin to point to a NaN in that case. Torchx already adheres to this behaviour.
I specifically changed the implementation such that MLIR aligns exactly with Jax.

Fix argmax/argmin behaviour with NaNs

---

exla/lib/exla/mlir/value.ex

The MLIR attribute is `compare_type`, not `comparison_type` :D

Properly set comparison type attribute on MLIR comparison ops

---

nx/lib/nx/constants.ex
nx/lib/nx/shared.ex
nx/lib/nx/type.ex
nx/test/nx/vectorize_test.exs

Fixes min / max value for 16 bit signed type, plus a small typo fix.
https://github.com/elixir-nx/nx/blob/2f44f4a9bf950ef4cbeb719785d9d9d881690bb9/exla/test/exla/defn/expr_test.exs#L1108-L1110
Thank you for reviewing.

Fix min / max value for 16 bit signed type

---

exla/lib/exla.ex
exla/test/exla/backend_test.exs
exla/test/exla/defn/expr_test.exs
nx/lib/nx.ex
nx/lib/nx/batch.ex
nx/lib/nx/defn.ex
nx/lib/nx/defn/kernel.ex
nx/lib/nx/lin_alg.ex
nx/lib/nx/random.ex
nx/lib/nx/serving.ex
nx/lib/nx/type.ex
nx/test/nx/container_test.exs
nx/test/nx/defn/evaluator_test.exs
nx/test/nx/defn/expr_test.exs
nx/test/nx/defn_test.exs
nx/test/nx/heatmap_test.exs
nx/test/nx/lazy_container_test.exs
nx/test/nx/optional_test.exs
nx/test/nx/random_test.exs
nx/test/nx/serving_test.exs
nx/test/nx/tensor_test.exs
nx/test/nx_test.exs
torchx/README.md
torchx/lib/torchx/backend.ex
torchx/mix.exs
torchx/test/torchx/nx_test.exs
torchx/test/torchx/random_test.exs

Nx and EXLA passes, but there are Torchx segfaults that I need to debug.

Default integers to 32-bit precision

---

exla/lib/exla/mlir/value.ex
exla/lib/exla/typespec.ex
exla/test/exla/defn/expr_test.exs
nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/constants.ex
nx/lib/nx/random.ex
nx/lib/nx/shared.ex
nx/lib/nx/type.ex
nx/test/nx_test.exs
torchx/c_src/torchx.cpp
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex

This PR adds support for an emulated FP8 in Nx's binary backend and adds support for FP8 operations from XLA. The FP8 type in EXLA is just there: `FP8E5M2` type. They have 3 of these FP8 types that we can configure if we want. 
In the binary backend the logic is in `shared.ex`. We have a function for interpreting erlang float's to a binary representation, and then we convert the binary chunks to f16 chunks and interpret those to f64.

Add initial FP8 support

---

nx/lib/nx/binary_backend/matrix.ex

fix: enforce always-positive ranges

---

exla/lib/exla.ex
exla/lib/exla/defn.ex
exla/test/exla_test.exs

`EXLA.to_mlir_module` wasn't working when being called from within a Defn compiler.
The new option adds the control needed for this to work.

fix: add support for defn compilation in EXLA.to_mlir_module

---

nx/lib/nx.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

fix: broadcast vectors for grad calculation

---

exla/Makefile

This moves the Makefile code that queries the system type and CUDA
availability under a guard for whether things are being cross-compiled.
If cross-compiled, then the settings are hardcoded. This should work in
non-Nerves compilation cases too, but those weren't tested.

Support cross-compilation for use with Nerves

---

nx/lib/nx/defn/sharding_compiler.ex
nx/lib/nx/defn/sharding_compiler/graph_splitter.ex
nx/lib/nx/defn/sharding_compiler/passes/graph_splitter.ex
nx/lib/nx/defn/sharding_compiler/passes/shard_propagation.ex
nx/test/nx/defn/sharding_compiler/passes/graph_splitter_test.exs

For compilation passes we'll have:
ShardingPropagation -> Part of what's present in ShardingCompiler currently -- basically, this is the purpose for `__compile__`. This is what propagates the sharding throughout the function.
GraphSplitter -> This PR (see below)
ShardingSeparation -> This is also present in ShardingCompiler, and is mostly what `__jit__` currently executes.
This PR adds the GraphSplitter pass that we can use to split computations based on
certain conditions (such as operations that require that a given dimension is not sharded).
It also builds out a list of computation specs that we can use to build an execution graph afterwards.
Each of these stages might have further fan-out depending on the subsequent ShardingSeparation pass.

feat: add graph splitter for all-gather/all-reduce operations

---

exla/Makefile
exla/README.md
exla/lib/exla/nif.ex
exla/mix.exs
exla/test/exla/device_memory_sharing_test.exs

fix: make exla build resilient to stale upgrades

---

exla/test/exla/nx_linalg_doctest_test.exs
nx/lib/nx/lin_alg.ex

The Nx.LinAlg.least_squares implementation assumed that for square matrices, it should fall back to Nx.LinAlg.solve.
However, the least squares solution is to minimize norm(Ax - b, 2), which isn't necessarily equal to solving Ax = b.
For example, if A = [[1, 2], [2, 4]] and b = [[3], [5]], Nx.LinAlg.solve will not be able to find a solution as the system doesn't have a valid solution. By going the pinv route, the minimal solution will be found.

fix: least_squares implementation

---

exla/c_src/exla/custom_calls.cc
exla/c_src/exla/custom_calls/lu.h
exla/c_src/exla/custom_calls/lu_bf16.cc
exla/c_src/exla/custom_calls/lu_f16.cc
exla/c_src/exla/custom_calls/lu_f32.cc
exla/c_src/exla/custom_calls/lu_f64.cc
exla/c_src/exla/custom_calls/qr.h
exla/lib/exla/defn.ex
exla/lib/exla/mlir/value.ex
exla/mix.exs
exla/test/exla/nx_linalg_doctest_test.exs

Adds a CPU custom call for Nx.LinAlg.lu, as that function is needed for Nx.LinAlg.determinant

feat(exla): add LU custom_call

---

nx/lib/nx.ex

The docs formatting for `Nx.all_close` was missing leading spaces for some of the iex examples, causing the docs to render like this:
---
Fixing the spacing issues makes it render like so:

Fix documentation formatting

---

nx/config/config.exs
nx/lib/nx/application.ex
nx/lib/nx/defn/sharding_compiler.ex
nx/lib/nx/defn/sharding_compiler/passes/graph_splitter.ex
nx/lib/nx/defn/sharding_compiler/passes/graph_splitter/stage.ex
nx/lib/nx/defn/sharding_compiler/passes/shard_propagation.ex
nx/lib/nx/defn/sharding_compiler/shard.ex
nx/lib/nx/defn/sharding_compiler/shard_execution.ex
nx/lib/nx/defn/sharding_compiler/shard_execution/argument_provider.ex
nx/lib/nx/defn/sharding_compiler/shard_execution/output_collector.ex
nx/lib/nx/defn/sharding_compiler/shard_execution/supervisor.ex
nx/lib/nx/defn/sharding_compiler/shard_registry.ex
nx/test/nx/defn/sharding_compiler/passes/graph_splitter_test.exs
nx/test/nx/defn/sharding_compiler/shard_execution_test.exs
nx/test/nx/defn/sharding_compiler_test.exs

Adds the initial version of the process communication structure for sharded execution.
Does not handle container outputs for the sharded function yet,
and also does not yet bring everything together into the compiler jit function.

feat: add shard execution workflow

---

nx/lib/nx/defn/expr.ex

Improves documentation rendering.

Use `@moduledoc` for `Nx.Defn.Expr`

---

nx/lib/nx/serving.ex
nx/test/nx/serving_test.exs

The Nx documentation states that it is important to use the same Nx version when using distributed servings. This leads to a problem for people using blue green deployments and trying to upgrade Nx. Without some special handling, you'll often run into situations where both the old and new nodes run in the cluster at the same time. Also, if you previously tried to run different servings on different machines, this wasn't really possible, as Nx would choose a random machine from pg, so each machine in the cluster running Nx would always have to run all servings.
By separating the pg groups by serving name, we can run different servings on different nodes while keeping the cluster connected. This also allows us to upgrade Nx in a blue green deployment by encoding the Nx version into the …

use serving name as pg group name

---

nx/lib/nx/defn/expr.ex
nx/lib/nx/type.ex
nx/test/nx/defn/expr_test.exs

fix: Nx.Defn.Expr will now promote constants based on the surrounding non-constant tensors for binary operations

---

nx/lib/nx.ex
nx/lib/nx/defn/expr.ex
nx/test/nx/defn_test.exs

This is an additional fix for #1570
`cond` will now use the correct representation for a given f32/f64/c64/c128 literal

fix: upcast floats in cond

---

nx/lib/nx/constants.ex
nx/lib/nx/defn/compiler.ex
nx/test/nx/defn_test.exs

If we rewrite the Nx defn AST during normalization to use the number values from :math or Complex for the arity-0 versions of i/e/pi, we can benefit from the previous pull requests on precision upcasting "for free".
This is implicit behavior, so I understand if we don't want this, but I believe it makes for a better UX.

feat: improve precision for nx constants

---

nx/lib/nx/defn/compiler.ex
nx/lib/nx/serving.ex
nx/test/nx/defn/compiler_test.exs

Sometimes, users will try to use invalid combos such as using Torchx as a defn compiler.
This PR transforms the generic FunctionClauseError into a more actionable message.

feat: add better errors for invalid compiler configurations

---

exla/c_src/exla/exla.cc
exla/c_src/exla/exla_cuda.cc
exla/c_src/exla/ipc.cc
exla/lib/exla/backend.ex
exla/test/exla/device_memory_sharing_test.exs
nx/lib/nx.ex
nx/lib/nx/backend.ex

See https://github.com/elixir-nx/nx/pull/1581#discussion_r1961343291.

Change Nx.to_pointer/2 and Nx.from_pointer/5 to raise on errors

---

exla/Makefile

This compiles the NIF shared library with `-fvisibility=hidden`, hiding all symbols other than the NIF init required by ERTS. I believe this is a good default for NIFs in general, it avoids symbol clashes (e.g. when multiple NIFs use the same external library, possibly with different versions), and it can also improve performance and linking time.
For more details see https://github.com/elixir-nx/fine/issues/2#issuecomment-2703366091.

Hide symbols from the NIF shared library

---

exla/test/exla/nx_linalg_doctest_test.exs

- **test: cholesky**
- **--version**
- **test: determinant**
- **test: matrix_power**
- **test: lu**
- **test: svd**
- **test: pinv**
- **chore: move triangular solve test to other category**

test(exla): add more tests for LinAlg functions 

---

exla/lib/exla/defn.ex
exla/test/exla/backend_test.exs

fix(exla): vectorized gather

---

torchx/c_src/torchx.cpp
torchx/mix.exs

Update Torch version to 2.7, and address namespace changes that occured in 2.6 which caused compilation failures. The linalg namespace appears to have been removed from the C++ api.

Increase Torch to latest version 2.7

---

torchx/README.md

Update CUDA versions in README for Torch 2.7 supported versions (11.8, 12.6, and 12.8).

Update Torchx README CUDA versions

---

nx/lib/nx.ex

The example was missing an extra tab causing the first line to be rendered as text instead of code. See https://hexdocs.pm/nx/Nx.html#functions-backend

Fix documentation example for Nx.backend_copy

---

torchx/README.md
torchx/mix.exs

Update LibTorch to version 2.8. This also requires updating the supported CUDA versions.
There was a breaking api change in LibTorch 2.5 release, so older versions will not compile.
https://pytorch.org/get-started/locally/

Update LibTorch to version 2.8

---

nx/lib/nx/defn/graph.ex
nx/test/nx/defn/graph_test.exs

Changes Nx.Defn.Graph so that splits can occur `:before` (what `true` did before) or `:after` a given node, `:both` (same as splitting before and after) or `:none` (no splits, same as what `false` did before)

feat: split before/after/both

---

nx/guides/getting_started/quickstart.livemd

At this point in the guide we have defined tensor as
tensor = Nx.tensor([[1, 2], [3, 4], [5, 6]], names: [:y, :x])
so using Nx.reshape(tensor, {1, 4}, names: [:batches, :values]) outputs an error. Changed it to {1, 4} to prevent this.

fix: quickstart example in getting_started guide
