elixir-nx/nx

c_src/exla/BUILD
c_src/exla/exla.cc
c_src/exla/exla_client.cc
c_src/exla/exla_client.h
c_src/exla/exla_device.cc
c_src/exla/exla_device.h
c_src/exla/exla_nif_util.cc
c_src/exla/exla_nif_util.h
lib/exla/client.ex
lib/exla/local_executable.ex
lib/exla/nif.ex
test/exla/client_test.exs
test/exla/local_executable_test.exs

CUDA compilation works!
The CUDA `run` tests are failing because of the lack of a CUDA allocator, but that was expected and the original intent of this PR. I'll get that fixed and mark this PR ready

CUDA Fixes

---

bench/dot_product.exs
bench/softmax.exs
c_src/exla/exla.cc
c_src/exla/exla_nif_util.cc
c_src/exla/exla_nif_util.h
lib/exla/builder.ex
lib/exla/nif.ex
lib/exla/op.ex
test/exla/builder_test.exs
test/exla/op_test.exs

Operating System: Linux
CPU Information: AMD Ryzen 5 3600 6-Core Processor
Number of Available Cores: 12
Available memory: 31.35 GB
Elixir 1.11.2
Erlang 23.1
GeForce RTX 2070, Compute Capability 7.5
**Softmax with `1_000_000` elements**
```
Name                          ips        average  deviation         median         99th %
xla gpu softmax ref        1.75 K      570.68 μs     ±7.34%      561.91 μs      803.86 μs
xla gpu softmax            509.07        1.96 ms     ±1.60%        1.96 ms        2.14 ms
xla cpu sotfmax ref        139.90        7.15 ms    ±14.65%        6.72 ms        9.93 ms
xla cpu softmax             93.45       10.70 ms    ±11.47%       10.44 ms       16.34 ms
elixir softmax               7.65      130.69 ms    ±10.08%      128.14 ms      170.95 ms
```
**Dot Product …

Softmax and Dot Product benchmarks

---

c_src/exla/BUILD
c_src/exla/exla.cc
c_src/exla/exla_allocator.cc
c_src/exla/exla_allocator.h
c_src/exla/exla_client.cc
c_src/exla/exla_client.h
c_src/exla/exla_device.cc
c_src/exla/exla_device.h
c_src/exla/exla_nif_util.cc
c_src/exla/exla_nif_util.h
examples/conditionals.exs
lib/exla/local_executable.ex
lib/exla/nif.ex
lib/exla/op.ex
test/exla/local_executable_test.exs

Right now just basic if-else style conditional. XLA also has another style of conditional that can be used to implement `cond` or maybe even `case`.

Conditionals

---

nx/README.md

Fix typo README.md

---

nx/lib/nx.ex

This PR adds several improvements and corrects a few spelling mistakes.

improve Nx documentation

---

exla/c_src/exla/exla.cc
exla/lib/exla/defn.ex
exla/lib/exla/lib.ex
exla/lib/exla/nif.ex
exla/lib/exla/op.ex
exla/test/exla/defn_expr_test.exs
exla/test/exla/executable_test.exs
nx/lib/nx.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/shared.ex

Just missing `erf_inv` implementation in Elixir

Add math ops

---

nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

These changes add the gradient for `Nx.tan/1` per #161.

gradient for tan(x)

---

nx/README.md

A great introductory resource!

Add link to Lambda Days talk by José

---

nx/README.md

Specify branch in mix dependency documentation

---

nx/lib/nx.ex
nx/test/nx_test.exs

Fix names bug on reshape with same shape

---

nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

These changes add gradients for sinh and cosh as part of issue #161

Hyperbolic grads

---

nx/test/nx/shared_test.exs

Removes tests for removed fallback functions

Remove unused fallback tests

---

exla/c_src/exla/exla_client.cc

Remove cases for nested tuples, resolves #260

Clean up cases in run

---

exla/c_src/exla/exla.cc
exla/lib/exla/defn.ex
exla/lib/exla/nif.ex
exla/lib/exla/op.ex
exla/test/exla/defn_expr_test.exs
nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/test/nx_test.exs

Resolves #181 
Hopefully I never have to write a convolution from scratch in my life again

Add groups to convolutions

---

nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/test/nx_test.exs

Nx.random_uniform/2 raises in BinaryBackend for non-float types

---

exla/lib/exla/defn.ex
exla/test/exla/defn_expr_test.exs
nx/lib/nx.ex
nx/lib/nx/binary_backend.ex

Resolves #262 
I think this is the most flexible way to support different kinds of convolutions. I tried to make the explanation as easy to understand as possible. Please let me know if it's confusing

Support convolution configurations

---

Makefile

This essentially describes (and fixes) the problem we're discussing in https://github.com/elixir-nx/nx/issues/294

Make various make targets symmetrical and usable from the top level.

---

nx/lib/nx.ex

Adds the missing norms for #157, which needed SVD to be ready

feat: add missing norms

---

nx/lib/nx.ex
nx/lib/nx/shape.ex
nx/test/nx_test.exs

Starting to refactor/cleanup some of the stuff in `Nx.Shape`

Move some shape logic to shape module

---

nx/lib/nx.ex
nx/lib/nx/shape.ex
nx/test/nx_test.exs

Clean up window shapes

---

nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

This resolves some issues with select grad

Fix select grad

---

nx/lib/nx/lin_alg.ex

This PR contains improvements to triangular solve.

Triangular solve improvements

---

nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/expr.ex

Add leftover options to to_batched_list

---

nx/lib/nx.ex

This PR adds Nx.stack as suggested in #379

feat: add Nx.stack/2

---

exla/c_src/exla/exla.cc
exla/lib/exla/defn.ex
exla/lib/exla/nif.ex
exla/lib/exla/op.ex
exla/lib/exla/shape.ex
exla/test/exla/defn_expr_test.exs
nx/.formatter.exs
nx/lib/nx.ex
nx/lib/nx/defn/compiler.ex
nx/lib/nx/defn/evaluator.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/kernel.ex
nx/lib/nx/defn/tree.ex
nx/lib/nx/shape.ex
nx/test/nx/defn/evaluator_test.exs
nx/test/nx/defn/expr_test.exs
nx/test/nx/defn/grad_test.exs
nx/test/nx/defn/tree_test.exs
nx/test/nx/defn_test.exs
nx/test/test_helper.exs

Add Nx.Defn.Kernel.while/3

---

nx/lib/nx/lin_alg.ex

As mentioned here: https://github.com/elixir-nx/nx/pull/387#issuecomment-835773806.
There were a bunch norms that did not return a float: `0`, `1`, `-1`,  `inf`, `-inf`. Alternatively the cast could be moved to `Nx.LinAlg.norm/2` which server as a common 'entrypoint' for all the implementations, then it's only implemented once. It's implicitly tested by the doctests.

Make Nx.LinAlg.norm/2 always return a float

---

exla/lib/exla/defn.ex
exla/test/exla/defn_expr_test.exs
nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn.ex
nx/lib/nx/defn/compiler.ex
nx/lib/nx/defn/evaluator.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/tree.ex
nx/test/nx/defn/evaluator_test.exs
nx/test/nx/defn/grad_test.exs
nx/test/nx/defn/tree_test.exs
nx/test/nx/defn_test.exs
nx/test/nx/lin_alg_test.exs

This pull request supports maps in defn, including inside block constructs, such as `if` and `map`.
Closes #208.

Maps in defn

---

nx/lib/nx.ex
nx/lib/nx/defn/compiler.ex
nx/lib/nx/defn/kernel.ex
nx/lib/nx/shape.ex
nx/lib/nx/tensor.ex
nx/test/nx/defn/grad_test.exs
nx/test/nx/lin_alg_test.exs
nx/test/nx_test.exs

Adds some property tests as discussed in #410

feat: add property tests for matrix decompositions

---

.github/workflows/ci.yml
nx/test/nx/defn/expr_test.exs

This PR introduces a basic CI workflow for Nx

feat: add github actions CI workflow

---

nx/lib/nx.ex
nx/lib/nx/binary_backend.ex

Truncate float to integer conversion

---

nx/lib/nx.ex
nx/lib/nx/shape.ex

Infer dimension on reshape

---

nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/kernel.ex
nx/test/nx/defn_test.exs

Resolves #361 
Sorry ahead of time for formatting issues :)
I think this covers the plan outlined in that issue

Add binary comparison operators a special forms

---

nx/lib/nx/binary_backend.ex
nx/test/nx_test.exs

Fix same padding window aggregate bug

---

exla/lib/exla/defn.ex
exla/test/exla/defn_expr_test.exs
nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/grad.ex
nx/lib/nx/defn/tree.ex
nx/test/nx/defn/grad_test.exs

Fix put_slice args

---

nx/lib/nx.ex

Fix typos and improve wording

---

exla/lib/exla/client.ex
exla/lib/exla/defn.ex
exla/test/exla/defn_expr_test.exs

This is a continuation of #447, adding the missing EXLA implementation

feat: add take along axis EXLA implementation

---

Makefile
exla/.gitignore
exla/Makefile
exla/Makefile.win
exla/README.md
exla/mix.exs
exla/mix.lock
exla/test/exla/defn_expr_test.exs

See https://github.com/elixir-nx/xla/pull/2.
Also, feel free to test the EXLA integration:
```elixir
Mix.install([
{:exla, "~> 0.1.0-dev", github: "jonatanklosko/nx", sparse: "exla", branch: "jk-xla-integration"},
{:nx, "~> 0.1.0-dev", github: "elixir-nx/nx", sparse: "nx", override: true}
], force: true)
defmodule Test do
import Nx.Defn
@defn_compiler EXLA
defn norm(x), do: Nx.dot(x, x)
end
Test.norm(Nx.tensor([1, 1]))
```
Yet to figure out windows, so I'm leaving this as a draft.

Integrate with elixir-nx/xla

---

exla/Makefile
exla/mix.exs
exla/mix.lock

Finalize XLA integration

---

nx/lib/nx/defn/expr.ex

fix: pass opts along to the backend implementation

---

exla/lib/exla/defn.ex

Handle scatter_add opts on EXLA side

---

nx/lib/nx/binary_backend.ex

As discussed in https://github.com/elixir-nx/nx/pull/458#discussion_r711698612

refactor: use binary-matching syntax for scatter-add impl

---

nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

feat: add gather grad

---

exla/c_src/exla/exla_client.cc

Resolves #432 
This avoids the additional `Relayout` and hence additional copy when executing computations by first checking if the shape needs to be re-laid out to begin with.

Avoid additional relayout if not necessary

---

exla/lib/exla/defn.ex
nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/grad.ex
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex
torchx/test/torchx/nx_doctest_test.exs

First step in the effort of making Torchx useable again. All tests now pass and can be added to the CI workflow.
Afterwards, some more tests will be added to ensure all functions are tested

chore: organize torchx tests

---

torchx/Makefile
torchx/c_src/torchx.cpp

Two minor fixes which silence all warnings which were being output by Torchx on my machine during compilation

fix: remove Torchx compilation warnings

---

nx/lib/nx.ex
nx/test/nx_test.exs

```elixir
iex(1)> Nx.iota({3, 3}) |> Nx.shuffle()
#Nx.Tensor<
s64[3][3]
[
[1, 8, 6],
[5, 0, 4],
[2, 3, 7]
]
>
iex(2)> Nx.iota({3, 3}) |> Nx.shuffle(axis: 0)
#Nx.Tensor<
s64[3][3]
[
[3, 1, 2],
[0, 7, 8],
[6, 4, 5]
]
>
iex(3)> Nx.iota({3, 3}) |> Nx.shuffle(axis: 1)
#Nx.Tensor<
s64[3][3]
[
[0, 2, 1],
[5, 4, 3],
[6, 8, 7]
]
>
```

Add Nx.shuffle/2

---

nx/lib/nx.ex
nx/test/nx_test.exs

This pr provides a implementation for Nx.diag.
Closes #517

Nx.diag implementation

---

nx/lib/nx/defn.ex
nx/lib/nx/defn/compiler.ex
nx/lib/nx/defn/evaluator.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/grad.ex
nx/lib/nx/defn/kernel.ex
nx/lib/nx/defn/token.ex
nx/lib/nx/defn/tree.ex
nx/test/nx/defn/evaluator_test.exs
nx/test/nx/defn/expr_test.exs
nx/test/nx/defn/grad_test.exs
nx/test/nx/defn/kernel_test.exs
nx/test/nx/defn/token_test.exs
nx/test/nx/defn/tree_test.exs

* All implementation for Nx is here, including grad and evaluator, only tests are pending
* Implementation for EXLA will be in another pull request
* `inspect_value/2` is also included for your debugging enjoying

Implement hooks and tokens for Nx

---

exla/lib/exla/defn.ex
exla/lib/exla/defn/buffer.ex
exla/lib/exla/defn/lock.ex
exla/lib/exla/defn/outfeed.ex
exla/lib/exla/defn/runner.ex
exla/lib/exla/defn/stream.ex
exla/test/exla/defn/api_test.exs
exla/test/exla/defn/lock_test.exs
nx/lib/nx/defn/expr.ex

Implement hooks for EXLA

---

exla/lib/exla/defn.ex
nx/lib/nx/defn/compiler.ex
nx/lib/nx/defn/evaluator.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/grad.ex
nx/lib/nx/defn/kernel.ex
nx/lib/nx/defn/tree.ex
nx/test/nx/defn/expr_test.exs
nx/test/nx/defn/grad_test.exs
nx/test/nx/defn/tree_test.exs
nx/test/nx/defn_test.exs

It is currently inefficient as the loop is executed twice, one for the value and one for the grad. I am working on cleaning it up next.

Gradient for while loops

---

exla/examples/mnist.exs
exla/lib/exla/defn.ex
exla/lib/exla/op.ex
nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/compiler.ex
nx/lib/nx/defn/evaluator.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/shared.ex
nx/lib/nx/type.ex
nx/test/nx/defn/grad_test.exs
nx/test/nx/lin_alg_test.exs
torchx/lib/torchx/backend.ex

Fix some inconsistency with terminology

---

torchx/CMakeLists.txt
torchx/Makefile
torchx/mix.exs

1. Don't read BUILD_EMBEDDED env var
2. Symlink/copy to priv/libtorch-vsn-target
for more stable versioning

Improvements to Torchx mix.exs

---

nx/test/nx/lin_alg_test.exs

Increase tolerance in cholesky property

---

torchx/lib/torchx/backend.ex
torchx/test/torchx_test.exs

fix(torchx): grow start index when length goes out of bounds

---

torchx/c_src/torchx.cpp
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex
torchx/test/torchx/backend_test.exs

Hi everyone,
This PR aims to add support for the `clip` method in TorchX(#504).

Feat(torchx): Add support for clip

---

exla/livebooks/rotating_image.livemd

I've created an example that shows the potential of EXLA and Nx in general. I think it might be worth adding this example. The main functionality of this example is to rotate image (in PNG format) by a given angle.

add livebook example

---

.github/workflows/ci.yml
torchx/CMakeLists.txt
torchx/Makefile.win
torchx/mix.exs
torchx/test/torchx/nx_doctest_test.exs

While I am here, change the URL pattern with version and target. At least this pattern works for 1.9.0, 1.9.1 and 1.10.0

Enable torchx build on Windows

---

nx/lib/nx.ex
torchx/test/torchx/nx_doctest_test.exs

Rename slice_axis to slice_along_axis

---

torchx/lib/torchx/backend.ex
torchx/test/torchx/nx_doctest_test.exs

add high tie_break support to argmin/argmix

---

nx/lib/nx.ex
nx/lib/nx/defn/compiler.ex

Resolves #550.
Basically just as described in the issue

Add load/save to Nx

---

nx/lib/nx.ex
nx/lib/nx/defn/kernel.ex

I just linked one to see if this is something we wanna do. If this looks like the right track, I can do a bunch more functions!

Link Nx functions to Nx.Defn.Kernel counterpart

---

exla/Makefile

@polvalente can you please give this a try locally?

Cache EXLA compilation across envs

---

torchx/mix.exs

> Mix.error("AA");
** (UndefinedFunctionError) function Mix.error/1 is undefined or private

Replace Mix.error with Mix.raise

---

torchx/c_src/torchx.cpp
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex
torchx/test/torchx/nx_doctest_test.exs

feat(torchx): put_slice

---

torchx/lib/torchx/backend.ex
torchx/test/torchx/nx_linalg_test.exs

Removes comment which was turned into issue #679 and un-skips test

chore: remove to-do comment for issue

---

exla/Makefile

Fix cache path

---

nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/shared.ex

This mimics the behavior from Jax and Pytorch, in which casting a complex to float returns its real component

feat: support typecasting from complex

---

nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/type.ex
nx/test/nx/complex_test.exs
torchx/test/torchx/nx_doctest_test.exs

Add Nx.conjugate

---

torchx/c_src/torchx.cpp
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex
torchx/test/torchx/nx_doctest_test.exs

Last PR of the series, in conjunction with #710

feat(torchx): add missing complex functions

---

nx/lib/nx.ex
nx/lib/nx/type.ex
nx/test/nx/complex_test.exs
torchx/test/torchx/nx_doctest_test.exs

Add Nx.phase

---

nx/lib/nx/lin_alg.ex
nx/test/nx/complex_test.exs
torchx/test/torchx/complex_test.exs

feat(complex): support Nx.LinAlg.norm

---

nx/lib/nx.ex
nx/lib/nx/binary_backend/matrix.ex
nx/lib/nx/lin_alg.ex
nx/test/nx/complex_test.exs
nx/test/nx/lin_alg_test.exs
torchx/test/torchx/complex_test.exs
torchx/test/torchx/nx_linalg_test.exs

feat(complex): add QR decomposition support

---

nx/lib/nx/binary_backend/matrix.ex
nx/lib/nx/lin_alg.ex
nx/test/nx/complex_test.exs
torchx/test/torchx/complex_test.exs

Related to https://github.com/elixir-nx/nx/issues/692

feat(complex): add support for triangular solve

---

nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

feat(grad): add lu complex grad

---

nx/lib/nx/binary_backend.ex
nx/lib/nx/lin_alg.ex
nx/test/nx/complex_test.exs
nx/test/nx/lin_alg_test.exs
torchx/test/torchx/complex_test.exs

feat(complex): support cholesky

---

nx/lib/nx.ex
nx/test/nx/complex_test.exs
torchx/test/torchx/nx_doctest_test.exs

Add complex tests for aggregate functions. See #695.

Add complex tests for aggregate functions

---

nx/lib/nx/binary_backend.ex
nx/lib/nx/type.ex
nx/test/nx/complex_test.exs

Adds support for complex numbers to the window functions. See #695.

Support complex numbers for window functions

---

nx/lib/nx/defn/compiler.ex
nx/test/nx/defn_test.exs

Raise more detailed errors when calling IO inside defn

---

nx/lib/nx/defn/compiler.ex
nx/test/nx/defn_test.exs

Raise a better error message for undefined functions in defn

---

nx/lib/nx.ex
nx/lib/nx/shape.ex
nx/test/nx/defn_test.exs

Raise a more specific error for tensors in a shape tuple

---

nx/lib/nx/defn/compiler.ex

Fix reference to Nx.Container in typespecs

---

nx/test/nx/defn/grad_test.exs

Add grad tests for Nx.window_sum, Nx.pad, and Nx.put_slice

---

exla/lib/exla/backend.ex
nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/mix.exs
torchx/c_src/torchx.cpp
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex

Closes #485.
I went with a longer naming (`cumulative_sum` rather than `cumsum`) for consistency with the window functions. If there is a preference for the shorter one let me know :)

Add cumulative functions

---

torchx/README.md
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex

docs: update Torchx docs

---

nx/lib/nx.ex

Properly normalize type in Nx.from_binary/3

---

exla/lib/exla/backend.ex
exla/test/exla/backend_test.exs

Implement EXLA.Backend.to_batched_list/3

---

exla/mix.lock
nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/lin_alg.ex
nx/lib/nx/shared.ex
nx/mix.exs
nx/mix.lock
nx/test/nx/complex_test.exs
nx/test/nx/non_finite_test.exs
torchx/mix.lock

blocked by https://github.com/elixir-nx/complex/pull/20

feat(non-finite): support non-finites in BinaryBackend

---

exla/c_src/exla/exla.cc
exla/examples/mnist.exs
exla/lib/exla/backend.ex
exla/lib/exla/defn.ex
exla/lib/exla/nif.ex
exla/lib/exla/op.ex
exla/mix.exs
exla/test/exla/backend_test.exs
exla/test/exla/defn/expr_test.exs
nx/lib/nx.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/grad.ex
nx/lib/nx/shared.ex
nx/mix.exs
nx/test/nx/complex_test.exs
nx/test/nx/defn/grad_test.exs
nx/test/nx/non_finite_test.exs
torchx/c_src/torchx.cpp
torchx/examples/mnist.exs
torchx/examples/mnist_manual.exs
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex
torchx/mix.exs
torchx/test/torchx/complex_test.exs
torchx/test/torchx/nx_doctest_test.exs
torchx/test/torchx/nx_test.exs

Nx.logistic to Nx.sigmoid

---

exla/lib/exla/backend.ex
exla/test/exla/backend_test.exs
nx/lib/nx/defn.ex
nx/lib/nx/defn/compiler.ex
nx/lib/nx/defn/composite.ex
nx/test/nx/defn_test.exs
nx/test/nx/optional_test.exs

Raise on Nx.Defn.Expr as JIT argument

---

nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/test/nx/defn/grad_test.exs
nx/test/nx_test.exs
torchx/lib/torchx/backend.ex

feat(complex): add support in Nx.conv

---

nx/lib/nx/binary_backend.ex
nx/test/nx_test.exs

Some edge cases failed when mixing real and complex tensors

fix(complex): Enum.reduce instead of Enum.sum

---

nx/lib/nx/binary_backend.ex

There is an error in how Nx is sampling random variables from a Normal distribution.  This request fixes it.
closes #809

changed sigma to variance in :rand.normal()

---

nx/test/nx_test.exs

test: add property test from random_uniform and random_normal

---

nx/lib/nx/defn/expr.ex
nx/test/nx/defn/expr_test.exs

Fix Nx.Defn.Expr.as_type to properly cast constants

---

nx/lib/nx.ex
nx/lib/nx/backend.ex
torchx/lib/torchx/backend.ex

feat: add :reverse to cumulative functions

---

nx/lib/nx/defn.ex
nx/lib/nx/defn/compiler.ex
nx/lib/nx/defn/kernel.ex
nx/lib/nx/lin_alg.ex
nx/lib/nx/shape.ex
nx/test/nx/defn/evaluator_test.exs
nx/test/nx/defn/kernel_test.exs
nx/test/nx/defn_test.exs
nx/test/nx/optional_test.exs
torchx/test/torchx/nx_linalg_test.exs

* inspect_expr and inspect_value have been deprecated
in favor of print_expr and print_value
* assert_shape and assert_shape_pattern have been deprecated
in favor of case+raise

Add raise/1-2 and inspect/1-2 to Nx.Defn.Kernel

---

exla/lib/exla/backend.ex
exla/lib/exla/defn.ex
exla/test/exla/defn/expr_test.exs
nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/shape.ex
nx/test/nx_test.exs
torchx/c_src/torchx.cpp
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex
torchx/test/torchx_test.exs

See #817.
Adds the `indexed_put` function.

Add `indexed_put`

---

nx/lib/nx.ex
nx/lib/nx/shape.ex
nx/test/nx_test.exs

Add `put_diagonal/3`

---

exla/mix.exs

Do not invoke deps.compile xla directly, closes #845

---

nx/guides/intro-to-nx.livemd

Fix mistake in intro-to-nx.livemd

---

nx/guides/intro-to-nx.livemd

Closes https://github.com/elixir-nx/nx/issues/854

Fix typo and replace def with defn

---

torchx/c_src/torchx.cpp
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex
torchx/test/torchx/nx_doctest_test.exs
torchx/test/torchx/nx_test.exs

feat(torchx): add batching support for dot

---

nx/lib/nx/binary_backend.ex
nx/test/nx/non_finite_test.exs

fix: plain non-finites in bin_reduce

---

exla/mix.lock
nx/mix.exs
nx/mix.lock
torchx/mix.lock

chore: update complex

---

nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

feat(grad): svd

---

nx/lib/nx/defn/compiler.ex

Allow floats in case/2 inside defn

---

nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

feat(grad): Nx.product

---

nx/lib/nx.ex

Closes #887.
See https://github.com/elixir-nx/nx/issues/887#issuecomment-1232755018.

Implement cumulative operations using associative scan

---

exla/lib/exla/defn.ex
exla/test/exla/defn/expr_test.exs

Fix EXLA compiler error with subsequent `if`s returning tuples

---

exla/bench/softmax.exs
exla/c_src/exla/exla.cc
exla/c_src/exla/exla_client.cc
exla/c_src/exla/exla_client.h

Run zero copy binaries

---

nx/lib/nx/defn/compiler.ex
nx/lib/nx/random.ex
nx/test/nx/random_test.exs

* Infer default type
* Downcast min/max + mean/std when appropriate
* Unify complex handling

Improve to random

---

exla/lib/exla/defn.ex
exla/test/exla/defn/expr_test.exs
nx/lib/nx/defn/evaluator.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/grad.ex
nx/lib/nx/defn/tree.ex
nx/test/nx/defn/evaluator_test.exs
nx/test/nx/defn/grad_test.exs
nx/test/nx/defn/tree_test.exs

Remove elements from cache if they are no longer going to be used

---

nx/lib/nx.ex

Closes #937
I implemented a version which accepts only one axis to aggregate. That's because it is unclear what this function would do for more than one dimension.

Add weighted_mean

---

exla/lib/exla/defn.ex
exla/mix.exs
nx/lib/nx.ex
nx/lib/nx/binary_backend.ex
nx/test/nx_test.exs
torchx/c_src/torchx.cpp
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex
torchx/mix.exs

feat: batched Nx.eye

---

nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

fix: sum clip grads wrt to min/max

---

exla/lib/exla/defn/lock.ex
exla/test/exla/defn/api_test.exs
exla/test/exla/defn/lock_test.exs
nx/CHANGELOG.md
nx/lib/nx.ex
nx/lib/nx/application.ex
nx/lib/nx/container.ex
nx/lib/nx/lazy_container.ex
nx/lib/nx/serving.ex
nx/mix.exs
nx/test/nx/serving_test.exs

Should be good for review. Only API docs missing and a Nx.Serving.Default implementation.

Nx.Serving type == :process

---

exla/c_src/exla/exla.cc
exla/lib/exla/nif.ex
exla/lib/exla/op.ex
exla/test/exla/defn/expr_test.exs
exla/test/exla/defn/lock_test.exs

Should help with gradient checkpoints

Add optimization barrier

---

nx/lib/nx.ex
nx/lib/nx/defn/compiler.ex
nx/lib/nx/shared.ex

Restore pdict state after defn compilation

---

nx/lib/nx/lin_alg/svd.ex

The latest fix was incorrect. The line that sets sign = 0 for 0 values
was indexed by the wrong tensor.

fix(svd): sign function indexed by correct values

---

nx/lib/nx/defn/compiler.ex
nx/lib/nx/lin_alg/svd.ex
nx/test/nx/lin_alg_test.exs

fix: add check for all-zeros svd

---

nx/lib/nx/lin_alg.ex
nx/test/nx/lin_alg_test.exs

fix: pinv edge cases

---

nx/lib/nx.ex

Respect fortran order in loading from numpy

---

nx/lib/nx.ex
nx/test/nx_test.exs

Add Nx.with_default_backend/2

---

nx/lib/nx/container.ex

Fix Nx.Container.traverse/3 typespec

---

nx/lib/nx.ex
nx/lib/nx/shape.ex
nx/test/nx_test.exs

Add axes to flatten

---

exla/Makefile

Makes the compile library symlink relative

---

nx/lib/nx.ex

Brings the implementation from polvalente/nx-signal#3

feat: add linspace

---

exla/Makefile
exla/mix.exs

See https://github.com/elixir-nx/nx/pull/1062#issuecomment-1386171551.

Fix relative EXLA symlinks

---

nx/lib/nx.ex

Based on the `reflect` mode for `numpy.pad`

feat: add Nx.reflect

---

nx/lib/nx/lin_alg.ex
nx/lib/nx/lin_alg/svd.ex
nx/lib/nx/shape.ex

As mentioned in [#73](https://github.com/elixir-nx/scholar/pull/73) I add `full_matrices?` option.

Add full_matrices? option to svd

---

nx/lib/nx.ex
nx/lib/nx/random.ex

Based on jax.random.permutation, so I can implement jax.random.choice aftewards

feat: add Nx.Random.shuffle

---

nx/lib/nx/lin_alg.ex
torchx/c_src/torchx.cpp
torchx/lib/torchx/backend.ex
torchx/mix.exs
torchx/mix.lock
torchx/test/torchx_test.exs

fix(torchx): support full_matrices

---

exla/c_src/exla/exla.cc
exla/examples/regression.exs
exla/lib/exla/backend.ex
exla/lib/exla/defn.ex
exla/lib/exla/nif.ex
exla/lib/exla/op.ex
exla/mix.exs
exla/test/exla/defn/api_test.exs
exla/test/exla/defn/expr_test.exs
nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/grad.ex
nx/lib/nx/defn/kernel.ex
nx/lib/nx/lin_alg.ex
nx/lib/nx/random.ex
nx/test/nx/complex_test.exs
nx/test/nx/defn/expr_test.exs
nx/test/nx/defn/grad_test.exs
nx/test/nx/defn_test.exs
nx/test/nx/non_finite_test.exs
torchx/c_src/torchx.cpp
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex
torchx/test/torchx/complex_test.exs
torchx/test/torchx/nx_test.exs

Closes https://github.com/elixir-nx/nx/issues/982.

Rename `Nx.power` to `Nx.pow`

---

nx/lib/nx/lin_alg.ex

ArgumentError comment for invalid mode test in `qr` function is Fixed.

Fix ArgumentError comment for invalid mode test in qr function

---

nx/lib/nx.ex

Proposal for vectorizing `iota`.
The same format merged here will be applied to `eye` and `linspace` since they are all creation functions, with the exception that the others also accept tensor inputs.

feat: vectorize Nx.iota

---

nx/lib/nx/serving.ex

I just started learning about how to use `Nx.Serving` by reading its docs. And I may have found some problems in the doc, but I'm not sure how to fix them.
I'm opening this PR to show some of the places where the doc may be outdated.

Some fixes to Nx.Serving's docs

---

nx/lib/nx/binary_backend/matrix.ex
nx/lib/nx/lin_alg.ex
nx/test/nx/lin_alg_test.exs

fix: linearly dependent determinant calculation

---

nx/lib/nx.ex
nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

closes #161
Only caveat is that I wasn't able to get reference values from Jax,
but the ideas here are basically the same as the grad for indexed_add,
which is the main implementation for these functions in Torchx.

feat(grad): window_scatter_min/max

---

nx/lib/nx.ex
nx/lib/nx/defn/evaluator.ex
nx/lib/nx/defn/expr.ex
nx/test/nx/defn/evaluator_test.exs

The changes to cond and while are temporary fixes until we support actual vectorization on those. As it stands, they still need the conditions to be scalars, but the clauses can be vectorized

Vectorize defn while

---

nx/lib/nx/serving.ex

Update serving docs

---

nx/lib/nx.ex
nx/lib/nx/shape.ex

feat: Allow non-batched inputs on indexed_add and indexed_put

---

nx/lib/nx.ex
nx/lib/nx/tensor.ex
nx/test/nx/vectorize_test.exs

also adds support for vectorized indices in slice

fix: vectorized access

---

nx/lib/nx.ex

Fix Nx.is_tensor for non-finite atoms

---

nx/lib/nx/lin_alg.ex
nx/test/nx/lin_alg_test.exs
torchx/lib/torchx/backend.ex
torchx/test/support/torchx_case.ex
torchx/test/torchx/nx_linalg_test.exs

fix: Nx.LinAlg.invert numerical stability

---

nx/lib/nx/tensor.ex
nx/test/nx/tensor_test.exs

fix: remove support for negative steps

---

nx/lib/nx.ex

docs: point to take_along_axis in argsort

---

nx/lib/nx.ex

This one will be helpful in K-fold implementation.

Add triu tril and tri functions

---

nx/lib/nx/defn/expr.ex

Refactor inspect implementation

---

torchx/mix.exs

Currently I get:
```
warning: this check/guard will always yield the same result
/Users/jonatanklosko/git/nx/torchx/mix.exs:48
```

Fix warning in torchx mix.exs

---

nx/lib/nx/serving.ex
nx/test/nx/serving_test.exs

Raise an error when serving stream is consumed in a different process

---

exla/test/exla/backend_test.exs
nx/lib/nx.ex

Fix Nx.pad/2 with different backends

---

nx/lib/nx/binary_backend.ex
nx/test/nx_test.exs

fix: Nx.clip for infinities (closes #1291)

---

exla/c_src/exla/exla.cc
exla/c_src/exla/mlir/builder.cc
exla/c_src/exla/mlir/builder.h
exla/lib/exla/defn.ex
exla/lib/exla/mlir/module.ex
exla/lib/exla/mlir/value.ex
exla/lib/exla/nif.ex
exla/test/exla/mlir/executable_test.exs

No precision config at the moment. Something with failed constraints. I can add that in after the fact

Add MLIR dot general

---

exla/c_src/exla/exla.cc
exla/c_src/exla/mlir/builder.cc
exla/c_src/exla/mlir/builder.h
exla/lib/exla/defn.ex
exla/lib/exla/mlir/value.ex
exla/lib/exla/nif.ex
exla/test/exla/mlir/executable_test.exs

Requires #1315 for broadcasting on_true and on_false together

Add MLIR select

---

nx/lib/nx/defn/grad.ex
nx/test/nx/defn/grad_test.exs

fix(vectorization): grad support

---

exla/c_src/exla/exla_ops.cc
exla/lib/exla/defn.ex
exla/lib/exla/op.ex
nx/lib/nx.ex
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend.ex
nx/lib/nx/defn/evaluator.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/defn/grad.ex
nx/lib/nx/defn/tree.ex
nx/lib/nx/shape.ex
torchx/c_src/torchx.cpp
torchx/lib/torchx.ex
torchx/lib/torchx/backend.ex

Adds Nx.fft2 and Nx.ifft2
Also adds support for :axis option in Nx.fft and Nx.ifft
Fixes an issue with optional callbacks where options weren't being passed properly through to compilers.
closes #1323

feat: add fft2 and ifft2

---

nx/lib/nx/batch.ex

Fix Nx.Batch padding with multi-device backends

---

exla/lib/exla/defn.ex
exla/lib/exla/mlir/value.ex
exla/lib/exla/op.ex
exla/test/exla/mlir/executable_test.exs
nx/lib/nx.ex
nx/lib/nx/binary_backend.ex

Fix sorting and always sort NaN last

---

nx/guides/intro-to-nx.livemd

Fixes the `Funs` module should import `Nx.Defn` in the intro Livebook.

---

exla/c_src/exla/exla.cc
exla/c_src/exla/mlir/builder.cc
exla/c_src/exla/mlir/builder.h
exla/c_src/exla/mlir/ops.cc
exla/c_src/exla/mlir/ops.h
exla/lib/exla/builder.ex
exla/lib/exla/defn.ex
exla/lib/exla/mlir/module.ex
exla/lib/exla/mlir/value.ex
exla/lib/exla/nif.ex
exla/test/exla/mlir/executable_test.exs

- feat: map working, reduce broken
- wip
- feat: working map (full) and reduce (as previously)

feat(mlir): map

---

exla/Makefile
exla/c_src/exla/exla.cc
exla/c_src/exla/exla_nif_util.cc
exla/c_src/exla/exla_nif_util.h
exla/c_src/exla/mlir/builder.cc
exla/c_src/exla/mlir/builder.h
exla/c_src/exla/mlir/ops.cc
exla/c_src/exla/mlir/ops.h
exla/lib/exla/builder.ex
exla/lib/exla/defn.ex
exla/lib/exla/defn/outfeed.ex
exla/lib/exla/mlir/module.ex
exla/lib/exla/mlir/value.ex
exla/lib/exla/nif.ex
exla/lib/exla/op.ex
exla/test.exs
exla/test/exla/mlir/executable_test.exs

- wip: mlir call
- wip
- feat: mlir call working
- test: add test
- chore: format

feat(mlir): call

---

exla/c_src/exla/exla.cc
exla/c_src/exla/mlir/builder.cc
exla/c_src/exla/mlir/builder.h
exla/c_src/exla/mlir/ops.cc
exla/c_src/exla/mlir/ops.h
exla/lib/exla/builder.ex
exla/lib/exla/computation.ex
exla/lib/exla/defn.ex
exla/lib/exla/mlir/module.ex
exla/lib/exla/mlir/value.ex
exla/lib/exla/nif.ex
exla/test.exs
exla/test/exla/mlir/executable_test.exs

- wip: mlir while
- feat: mlir while

feat(mlir): while

---

nx/lib/nx/defn/expr.ex
nx/test/nx/vectorize_test.exs

fix: vectorized cond with numeric literal leaf

---

exla/c_src/exla/mlir/builder.cc
exla/lib/exla/defn.ex
exla/test/exla/mlir/nx_doctest_test.exs

- wip: fix mlir all close
- fix: bin op typing
- chore: unskip tests
- chore: move some test skips around

fix(mlir): all_close and bin op broadcasting

---

exla/c_src/exla/mlir/builder.cc

- fix: load all dialects up front
- fix: load chlo up front

fix: load all dialects up front

---

exla/lib/exla/defn.ex
exla/lib/exla/mlir/value.ex
exla/test/exla/mlir/nx_doctest_test.exs

- fix: gather, take, take along axis
- chore: unify clauses
- chore: unskip more tests

fix(mlir): gather, take, take_along_axis

---

exla/c_src/exla/exla.cc
exla/c_src/exla/mlir/builder.cc
exla/c_src/exla/mlir/builder.h
exla/c_src/exla/mlir/ops.cc
exla/c_src/exla/mlir/ops.h
exla/lib/exla/defn.ex
exla/lib/exla/lib.ex
exla/lib/exla/mlir/value.ex
exla/lib/exla/nif.ex
exla/test/exla/mlir/nx_doctest_test.exs
exla/top_k.exs

- feat(mlir): sort, argsort, mode
- wip: top_k
- feat: top_k

feat(mlir): add last missing operations

---

.github/workflows/ci.yml
exla/test/exla/defn/api_test.exs
exla/test/exla/defn/expr_test.exs
exla/test/exla/defn/vectorize_test.exs
exla/test/exla/random_test.exs
exla/test/exla/serving_test.exs
exla/test/exla_test.exs
exla/test/test_helper.exs

- chore: skip all mlir tests that are broken
- feat: add mlir to ci

chore: add MLIR to CI

---

exla/lib/exla/defn.ex
exla/lib/exla/mlir/value.ex
exla/test/exla/backend_test.exs
exla/test/exla/defn/expr_test.exs
exla/test/test_helper.exs

- feat: unksip arithmetic error tests
- fix: precision test
- fix: sign for unsigned input

fix(mlir): pass some skipped tests

---

exla/lib/exla/builder.ex
exla/lib/exla/defn.ex
exla/lib/exla/mlir/value.ex
exla/test/exla/mlir/compiler_test.exs

More work towards #1420. Still not there yet, but this is a case we need support nevertheless

fix(mlir): cond with possibly nested container result

---

exla/lib/exla/builder.ex
exla/lib/exla/defn.ex
exla/test/exla/defn/expr_test.exs
exla/test/exla/mlir/nx_linalg_doctest_test.exs

- wip: qr test passes
- feat: all tests pass!
closes #1420

feat(mlir): Nx.LinAlg.qr support

---

exla/c_src/exla/exla.cc
exla/c_src/exla/exla_ops.cc
exla/c_src/exla/exla_ops.h
exla/lib/exla/backend.ex
exla/lib/exla/defn.ex
exla/lib/exla/nif.ex
exla/lib/exla/op.ex
exla/test/exla/backend_test.exs
exla/test/exla/defn/expr_test.exs
exla/test/exla/mlir/nx_linalg_doctest_test.exs
nx/lib/nx/backend.ex
nx/lib/nx/binary_backend/matrix.ex
nx/lib/nx/defn/expr.ex
nx/lib/nx/lin_alg.ex
nx/lib/nx/lin_alg/eigh.ex

feat: Nx.LinAlg.eigh as optional callback

---

nx/lib/nx/type.ex

The current values are actually infinities.

Fix min and max finite values for :bf16

---

exla/lib/exla/defn.ex
exla/test/exla/defn/api_test.exs
exla/test/exla/defn/expr_test.exs
exla/test/exla/random_test.exs
exla/test/test_helper.exs

- fix(mlir): while and cond edge cases
- chore: unskip more tests

fix(mlir): while and cond computation edge cases

---

exla/lib/exla/computation.ex
exla/lib/exla/defn.ex
exla/test/exla/defn/api_test.exs
exla/test/exla/defn/vectorize_test.exs
exla/test/exla/serving_test.exs
exla/test/test_helper.exs

- feat(mlir): support tokens in cond
- chore: remove stray describetag

feat(mlir): support tokens in cond

---

exla/c_src/exla/exla.cc
exla/c_src/exla/mlir/builder.cc
exla/c_src/exla/mlir/builder.h
exla/c_src/exla/mlir/ops.cc
exla/c_src/exla/mlir/ops.h
exla/lib/exla/defn.ex
exla/lib/exla/mlir/function.ex
exla/lib/exla/mlir/region.ex
exla/lib/exla/mlir/value.ex
exla/lib/exla/nif.ex
exla/test/exla/executable_test.exs

- refactor: use new push_region nif for if_op
- wip
- refactor: while with regions

refactor(mlir): WhileOp with regions instead of functions

---

exla/c_src/exla/mlir/builder.cc
exla/lib/exla/defn.ex

The generated modules had lots of u8 -> u1 -> u8 or u1 -> u8 -> u1 conversions
that I managed to trim out, especially in while and cond.
The binary operation broadcasting is now only conditionally done,
and we do the operations directly in the output type instead.:

refactor(mlir): some improvements to the graph generation

---

exla/test/exla/defn/expr_test.exs
nx/lib/nx/defn/expr.ex

fix: while with vectorized cond inside

---

exla/lib/exla/mlir/module.ex
exla/lib/exla/mlir/value.ex

- feat: update reduce
- feat: update all dense i64 to array i64

feat: update MLIR notation to latest stablehlo spec"

---

nx/guides/exercises/exercises-1-20.livemd

> Create a tensor with values ranging from 10 to 49.
Solution 1 is
```elixir
Nx.iota({39})
|> Nx.add(10)
```
Which produces
```elixir
s64[39]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]
>
```
Other solutions are inclusive ranges, so the the solution should be
```elixir
Nx.iota({40})
|> Nx.add(10)
```

Fix Nx exercises solution

---

nx/lib/nx/lin_alg/eigh.ex

- fix: force hessenberg range to be positive
- chore: make defn private

fix: force hessenberg range to be positive

---

exla/c_src/exla/custom_calls.cc
exla/c_src/exla/custom_calls.h
exla/lib/exla/defn.ex
exla/lib/exla/mlir/value.ex

- feat(exla): add custom callback for eigh
- chore: remove dbg calls

feat(exla): add custom callback for Nx.LinAlg.eigh

---

exla/c_src/exla/exla.cc

chore(exla): upgrade NIFs

---

exla/lib/exla/device_buffer.ex
exla/lib/exla/mlir/module.ex
exla/test/exla/defn/lock_test.exs
exla/test/exla/defn/vectorize_test.exs

Fix various typos in exla/

---

nx/lib/nx/backend.ex
nx/lib/nx/constants.ex
nx/lib/nx/defn.ex
nx/lib/nx/defn/kernel.ex
nx/lib/nx/defn/tree.ex
nx/lib/nx/lin_alg/svd.ex
nx/lib/nx/shared.ex
nx/test/nx/lazy_container_test.exs
nx/test/nx/optional_test.exs

Fix various typos in nx/

---

exla/CHANGELOG.md
exla/mix.exs
exla/mix.lock

Added some changelog entries from XLA for visibility.

Bump xla dependency

---

nx/lib/nx/lin_alg.ex
nx/test/nx/lin_alg_test.exs

fix: Nx.LinAlg.norm axes support

---

exla/c_src/exla/custom_calls.cc
exla/lib/exla/mlir/value.ex

Pass custom call sizes as unsigned integers

---

nx/test/nx/serving_test.exs

Fixes two serving tests that fail extremely often on CI :)

Fix race condition in serving tests

---

exla/lib/exla.ex

See https://github.com/elixir-nx/xla/pull/103.

Link to versioned XLA docs

---

exla/Makefile

fix: allow users to pass CFLAGS

---

.github/workflows/ci.yml
nx/mix.exs

CI should now only run for subdirectories with changed files

chore: skip CI for unchanged subdirs

---

nx/lib/nx/shape.ex

fix: validate interior padding
